// @generated by dsp/regen.sh from dsp/distort.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "distort"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ec -ct 1 -cn DistortDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */
#[repr(C)]
pub struct DistortDsp {
	fHslider0: F32,
	fSlow0: F32,
	fHslider1: F32,
	iSlow1: i32,
	iSlow2: i32,
	iSlow3: i32,
	iSlow4: i32,
	fHslider2: F32,
	fSlow5: F32,
	fSlow6: F32,
	fSlow7: F32,
	fSlow8: F32,
	fHslider3: F32,
	fSlow9: F32,
	fSlow10: F32,
	fVec0: [F32;2],
	fSlow11: F32,
	iSlow12: i32,
	iSlow13: i32,
	fSampleRate: i32,
}

pub type FaustFloat = F32;
fn DistortDsp_faustpower2_f(value: F32) -> F32 {
	return value * value;
}
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 4;
pub const FAUST_PASSIVES: usize = 0;


impl DistortDsp {
		
	pub fn new() -> DistortDsp { 
		DistortDsp {
			fHslider0: 0.0,
			fSlow0: 0.0,
			fHslider1: 0.0,
			iSlow1: 0,
			iSlow2: 0,
			iSlow3: 0,
			iSlow4: 0,
			fHslider2: 0.0,
			fSlow5: 0.0,
			fSlow6: 0.0,
			fSlow7: 0.0,
			fSlow8: 0.0,
			fHslider3: 0.0,
			fSlow9: 0.0,
			fSlow10: 0.0,
			fVec0: [0.0;2],
			fSlow11: 0.0,
			iSlow12: 0,
			iSlow13: 0,
			fSampleRate: 0,
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("aanl.lib/ADAA1:author", r"Dario Sanfilippo");
		m.declare("aanl.lib/ADAA1:copyright", r"Copyright (C) 2021 Dario Sanfilippo     <sanfilippo.dario@gmail.com>");
		m.declare("aanl.lib/ADAA1:license", r"MIT License");
		m.declare("aanl.lib/arctan:author", r"Dario Sanfilippo");
		m.declare("aanl.lib/arctan:copyright", r"Copyright (C) 2021 Dario Sanfilippo     <sanfilippo.dario@gmail.com>");
		m.declare("aanl.lib/arctan:license", r"MIT License");
		m.declare("aanl.lib/hardclip:author", r"Dario Sanfilippo");
		m.declare("aanl.lib/hardclip:copyright", r"Copyright (C) 2021 Dario Sanfilippo     <sanfilippo.dario@gmail.com>");
		m.declare("aanl.lib/hardclip:license", r"MIT License");
		m.declare("aanl.lib/name", r"Faust Antialiased Nonlinearities");
		m.declare("aanl.lib/parabolic:author", r"Dario Sanfilippo");
		m.declare("aanl.lib/parabolic:copyright", r"Copyright (C) 2021 Dario Sanfilippo     <sanfilippo.dario@gmail.com>");
		m.declare("aanl.lib/parabolic:license", r"MIT License");
		m.declare("aanl.lib/sinarctan:author", r"Dario Sanfilippo");
		m.declare("aanl.lib/sinarctan:copyright", r"Copyright (C) 2021 Dario Sanfilippo     <sanfilippo.dario@gmail.com>");
		m.declare("aanl.lib/sinarctan:license", r"MIT License");
		m.declare("aanl.lib/tanh1:author", r"Dario Sanfilippo");
		m.declare("aanl.lib/tanh1:copyright", r"Copyright (C) 2021 Dario Sanfilippo     <sanfilippo.dario@gmail.com>");
		m.declare("aanl.lib/tanh1:license", r"MIT License");
		m.declare("aanl.lib/version", r"1.4.1");
		m.declare("basics.lib/name", r"Faust Basic Element Library");
		m.declare("basics.lib/version", r"1.21.0");
		m.declare("compile_options", r"-lang rust -ec -ct 1 -cn DistortDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0");
		m.declare("filename", r"distort.dsp");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"distort");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 1.0;
		self.fHslider1 = 0.0;
		self.fHslider2 = 0.0;
		self.fHslider3 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.fVec0[l0 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		DistortDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("distort");
		ui_interface.add_horizontal_slider("a_distort", ParamIndex(0), 0.0, 0.0, 1e+02, 0.001);
		ui_interface.add_horizontal_slider("b_distortvol", ParamIndex(1), 1.0, 0.0, 2.0, 0.001);
		ui_interface.add_horizontal_slider("c_distortmode", ParamIndex(2), 0.0, 0.0, 5.0, 1.0);
		ui_interface.add_horizontal_slider("d_asym", ParamIndex(3), 0.0, -1.0, 1.0, 0.001);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			1 => Some(self.fHslider0),
			2 => Some(self.fHslider1),
			0 => Some(self.fHslider2),
			3 => Some(self.fHslider3),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			1 => { self.fHslider0 = value }
			2 => { self.fHslider1 = value }
			0 => { self.fHslider2 = value }
			3 => { self.fHslider3 = value }
			_ => {}
		}
	}
	
	pub fn control(&mut self) {
		// Obtaining locks on 0 static var(s)
	self.fSlow0 = self.fHslider0;
		self.iSlow1 = (self.fHslider1) as i32;
		self.iSlow2 = (self.iSlow1 >= 3) as i32;
		self.iSlow3 = (self.iSlow1 >= 2) as i32;
		self.iSlow4 = (self.iSlow1 >= 1) as i32;
		self.fSlow5 = F32::max(self.fHslider2, 0.0);
		self.fSlow6 = self.fSlow5 + 1.0;
		self.fSlow7 = F32::powf(self.fSlow6, -0.12);
		self.fSlow8 = self.fSlow6 * self.fSlow7;
		self.fSlow9 = self.fHslider3;
		self.fSlow10 = 0.05 / (0.05 * self.fSlow5 + 1.0);
		self.fSlow11 = 0.63661975 * self.fSlow7;
		self.iSlow12 = (self.iSlow1 >= 5) as i32;
		self.iSlow13 = (self.iSlow1 >= 4) as i32;
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = *input0;
			let mut fTemp1: F32 = self.fSlow9 + fTemp0 + 0.05;
			let mut fTemp2: F32 = self.fSlow9 + fTemp0;
			let mut fTemp3: F32 = self.fSlow6 * fTemp2;
			self.fVec0[0] = fTemp3;
			let mut fTemp4: F32 = fTemp3 - self.fVec0[1];
			let mut iTemp5: i32 = (F32::abs(fTemp4) <= 0.001) as i32;
			let mut fTemp6: F32 = fTemp3 + self.fVec0[1];
			let mut fTemp7: F32 = 0.5 * fTemp6;
			let mut fTemp8: F32 = DistortDsp_faustpower2_f(fTemp3);
			let mut fTemp9: F32 = fTemp8 + 1.0;
			let mut fTemp10: F32 = DistortDsp_faustpower2_f(self.fVec0[1]);
			let mut fTemp11: F32 = fTemp10 + 1.0;
			let mut fTemp12: F32 = self.fSlow6 * fTemp2 * (((fTemp3 > 0.0) as i32) - ((fTemp3 < 0.0) as i32)) as F32;
			let mut fTemp13: F32 = self.fVec0[1] * (((self.fVec0[1] > 0.0) as i32) - ((self.fVec0[1] < 0.0) as i32)) as F32;
			let mut fTemp14: F32 = F32::abs(fTemp3);
			let mut fTemp15: F32 = F32::abs(self.fVec0[1]);
			let mut fTemp16: F32 = F32::abs(fTemp7);
			*output0 = self.fSlow0 * (if self.iSlow2 != 0 {(if self.iSlow12 != 0 {self.fSlow7 * (if iTemp5 != 0 {0.5 * (fTemp6 / F32::sqrt(DistortDsp_faustpower2_f(fTemp7) + 1.0))} else {(F32::sqrt(fTemp9) - F32::sqrt(fTemp11)) / fTemp4})} else {(if self.iSlow13 != 0 {self.fSlow7 * (if iTemp5 != 0 {(if (fTemp16 <= 2.0) as i32 != 0 {0.5 * fTemp6 * (1.0 - 0.25 * fTemp16)} else {(((fTemp7 > 0.0) as i32) - ((fTemp7 < 0.0) as i32)) as F32})} else {((if (fTemp14 <= 2.0) as i32 != 0 {-(0.083333336 * fTemp8 * (fTemp12 + -6.0))} else {fTemp14}) - (if (fTemp15 <= 2.0) as i32 != 0 {-(0.083333336 * fTemp10 * (fTemp13 + -6.0))} else {fTemp15})) / fTemp4})} else {self.fSlow7 * (if iTemp5 != 0 {F32::max(-1.0, F32::min(1.0, fTemp7))} else {((if ((fTemp3 <= 1.0) as i32) & ((fTemp3 >= -1.0) as i32) != 0 {0.5 * fTemp8} else {fTemp12 + -0.5}) - (if ((self.fVec0[1] <= 1.0) as i32) & ((self.fVec0[1] >= -1.0) as i32) != 0 {0.5 * fTemp10} else {fTemp13 + -0.5})) / fTemp4})})})} else {(if self.iSlow3 != 0 {self.fSlow11 * (if iTemp5 != 0 {F32::atan(fTemp7)} else {(self.fSlow6 * fTemp2 * F32::atan(fTemp3) - (self.fVec0[1] * F32::atan(self.fVec0[1]) + 0.5 * (F32::log(fTemp9, std::f32::consts::E) - F32::log(fTemp11, std::f32::consts::E)))) / fTemp4})} else {(if self.iSlow4 != 0 {self.fSlow7 * (if iTemp5 != 0 {F32::tanh(fTemp7)} else {(F32::log(F32::min(3.4028235e+38, F32::cosh(fTemp3)), std::f32::consts::E) - F32::log(F32::min(3.4028235e+38, F32::cosh(self.fVec0[1])), std::f32::consts::E)) / fTemp4})} else {self.fSlow8 * (fTemp1 / (self.fSlow5 * F32::abs(fTemp1) + 1.0) - self.fSlow10)})})});
			self.fVec0[1] = self.fVec0[0];
		}
		
	}

}

impl FaustDsp for DistortDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
