// @generated by dsp/regen.sh from dsp/eq.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "eq"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ct 1 -cn EqDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */
#[repr(C)]
pub struct EqDsp {
	fSampleRate: i32,
	fConst0: F32,
	fConst1: F32,
	fHslider0: F32,
	fHslider1: F32,
	fHslider2: F32,
	fVec0: [F32;2],
	fRec2: [F32;2],
	fHslider3: F32,
	fRec3: [F32;2],
	fHslider4: F32,
	fHslider5: F32,
	fConst2: F32,
	fRec1: [F32;3],
	fVec1: [F32;2],
	fRec0: [F32;2],
	fHslider6: F32,
	fRec4: [F32;2],
}

pub type FaustFloat = F32;
fn EqDsp_faustpower2_f(value: F32) -> F32 {
	return value * value;
}
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 7;
pub const FAUST_PASSIVES: usize = 0;


impl EqDsp {
		
	pub fn new() -> EqDsp { 
		EqDsp {
			fSampleRate: 0,
			fConst0: 0.0,
			fConst1: 0.0,
			fHslider0: 0.0,
			fHslider1: 0.0,
			fHslider2: 0.0,
			fVec0: [0.0;2],
			fRec2: [0.0;2],
			fHslider3: 0.0,
			fRec3: [0.0;2],
			fHslider4: 0.0,
			fHslider5: 0.0,
			fConst2: 0.0,
			fRec1: [0.0;3],
			fVec1: [0.0;2],
			fRec0: [0.0;2],
			fHslider6: 0.0,
			fRec4: [0.0;2],
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("analyzers.lib/name", r"Faust Analyzer Library");
		m.declare("analyzers.lib/version", r"1.2.0");
		m.declare("basics.lib/name", r"Faust Basic Element Library");
		m.declare("basics.lib/version", r"1.21.0");
		m.declare("compile_options", r"-lang rust -ct 1 -cn EqDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0");
		m.declare("filename", r"eq.dsp");
		m.declare("filters.lib/filterbank:author", r"Julius O. Smith III");
		m.declare("filters.lib/filterbank:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/filterbank:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/fir:author", r"Julius O. Smith III");
		m.declare("filters.lib/fir:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/fir:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/highpass:author", r"Julius O. Smith III");
		m.declare("filters.lib/highpass:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/highshelf:author", r"Julius O. Smith III");
		m.declare("filters.lib/highshelf:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/highshelf:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/iir:author", r"Julius O. Smith III");
		m.declare("filters.lib/iir:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/iir:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/lowpass0_highpass1", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowpass0_highpass1:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowpass:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowpass:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowpass:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/lowshelf:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowshelf:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowshelf:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/name", r"Faust Filters Library");
		m.declare("filters.lib/peak_eq:author", r"Julius O. Smith III");
		m.declare("filters.lib/peak_eq:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/peak_eq:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/peak_eq_cq:author", r"Julius O. Smith III");
		m.declare("filters.lib/peak_eq_cq:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/peak_eq_cq:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf1:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf1:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf1:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf1s:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf1s:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf1s:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf2:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf2:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf2:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf2s:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf2s:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf2s:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/version", r"1.7.1");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"eq");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 5e+03;
		self.fHslider1 = 1e+03;
		self.fHslider2 = 2e+02;
		self.fHslider3 = 0.0;
		self.fHslider4 = 0.0;
		self.fHslider5 = 0.7;
		self.fHslider6 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.fVec0[l0 as usize] = 0.0;
		}
		for l1 in 0..2 {
			self.fRec2[l1 as usize] = 0.0;
		}
		for l2 in 0..2 {
			self.fRec3[l2 as usize] = 0.0;
		}
		for l3 in 0..3 {
			self.fRec1[l3 as usize] = 0.0;
		}
		for l4 in 0..2 {
			self.fVec1[l4 as usize] = 0.0;
		}
		for l5 in 0..2 {
			self.fRec0[l5 as usize] = 0.0;
		}
		for l6 in 0..2 {
			self.fRec4[l6 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = 3.1415927 / self.fConst0;
		self.fConst2 = 6.2831855 / self.fConst0;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		EqDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("eq");
		ui_interface.add_horizontal_slider("a_lo_db", ParamIndex(0), 0.0, -24.0, 24.0, 0.001);
		ui_interface.add_horizontal_slider("b_lo_f", ParamIndex(1), 2e+02, 2e+01, 2e+03, 0.001);
		ui_interface.add_horizontal_slider("c_mid_db", ParamIndex(2), 0.0, -24.0, 24.0, 0.001);
		ui_interface.add_horizontal_slider("d_mid_f", ParamIndex(3), 1e+03, 1e+02, 1e+04, 0.001);
		ui_interface.add_horizontal_slider("e_hi_db", ParamIndex(4), 0.0, -24.0, 24.0, 0.001);
		ui_interface.add_horizontal_slider("f_hi_f", ParamIndex(5), 5e+03, 1e+03, 2e+04, 0.001);
		ui_interface.add_horizontal_slider("g_mid_q", ParamIndex(6), 0.7, 0.2, 8.0, 0.001);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			5 => Some(self.fHslider0),
			3 => Some(self.fHslider1),
			1 => Some(self.fHslider2),
			0 => Some(self.fHslider3),
			2 => Some(self.fHslider4),
			6 => Some(self.fHslider5),
			4 => Some(self.fHslider6),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			5 => { self.fHslider0 = value }
			3 => { self.fHslider1 = value }
			1 => { self.fHslider2 = value }
			0 => { self.fHslider3 = value }
			2 => { self.fHslider4 = value }
			6 => { self.fHslider5 = value }
			4 => { self.fHslider6 = value }
			_ => {}
		}
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let mut fSlow0: F32 = 1.0 / F32::tan(self.fConst1 * self.fHslider0);
		let mut fSlow1: F32 = 1.0 / (fSlow0 + 1.0);
		let mut fSlow2: F32 = 1.0 - fSlow0;
		let mut fSlow3: F32 = self.fHslider1;
		let mut fSlow4: F32 = F32::tan(self.fConst1 * fSlow3);
		let mut fSlow5: F32 = 2.0 * (1.0 - 1.0 / EqDsp_faustpower2_f(fSlow4));
		let mut fSlow6: F32 = 1.0 / F32::tan(self.fConst1 * self.fHslider2);
		let mut fSlow7: F32 = 1.0 / (fSlow6 + 1.0);
		let mut fSlow8: F32 = 1.0 - fSlow6;
		let mut fSlow9: F32 = F32::powf(1e+01, 0.05 * self.fHslider3);
		let mut fSlow10: F32 = 1.0 / fSlow4;
		let mut fSlow11: F32 = self.fHslider4;
		let mut iSlow12: i32 = (fSlow11 > 0.0) as i32;
		let mut fSlow13: F32 = self.fHslider5 * F32::sin(self.fConst2 * fSlow3);
		let mut fSlow14: F32 = self.fConst1 * (fSlow3 * F32::powf(1e+01, 0.05 * F32::abs(fSlow11)) / fSlow13);
		let mut fSlow15: F32 = self.fConst1 * (fSlow3 / fSlow13);
		let mut fSlow16: F32 = (if iSlow12 != 0 {fSlow15} else {fSlow14});
		let mut fSlow17: F32 = fSlow10 * (fSlow10 - fSlow16) + 1.0;
		let mut fSlow18: F32 = fSlow10 * (fSlow10 + fSlow16) + 1.0;
		let mut fSlow19: F32 = (if iSlow12 != 0 {fSlow14} else {fSlow15});
		let mut fSlow20: F32 = fSlow10 * (fSlow10 + fSlow19) + 1.0;
		let mut fSlow21: F32 = fSlow10 * (fSlow10 - fSlow19) + 1.0;
		let mut fSlow22: F32 = F32::powf(1e+01, 0.05 * self.fHslider6);
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = *input0;
			self.fVec0[0] = fTemp0;
			self.fRec2[0] = -(fSlow7 * (fSlow8 * self.fRec2[1] - fSlow6 * (fTemp0 - self.fVec0[1])));
			self.fRec3[0] = -(fSlow7 * (fSlow8 * self.fRec3[1] - (fTemp0 + self.fVec0[1])));
			let mut fTemp1: F32 = fSlow5 * self.fRec1[1];
			self.fRec1[0] = self.fRec2[0] + fSlow9 * self.fRec3[0] - (self.fRec1[2] * fSlow17 + fTemp1) / fSlow18;
			let mut fTemp2: F32 = (fTemp1 + self.fRec1[0] * fSlow20 + self.fRec1[2] * fSlow21) / fSlow18;
			self.fVec1[0] = fTemp2;
			self.fRec0[0] = -(fSlow1 * (fSlow2 * self.fRec0[1] - (fTemp2 + self.fVec1[1])));
			self.fRec4[0] = -(fSlow1 * (fSlow2 * self.fRec4[1] - fSlow0 * (fTemp2 - self.fVec1[1])));
			*output0 = self.fRec0[0] + fSlow22 * self.fRec4[0];
			self.fVec0[1] = self.fVec0[0];
			self.fRec2[1] = self.fRec2[0];
			self.fRec3[1] = self.fRec3[0];
			self.fRec1[2] = self.fRec1[1];
			self.fRec1[1] = self.fRec1[0];
			self.fVec1[1] = self.fVec1[0];
			self.fRec0[1] = self.fRec0[0];
			self.fRec4[1] = self.fRec4[0];
		}
		
	}

}

impl FaustDsp for EqDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
