// @generated by dsp/regen.sh from dsp/fshift.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "fshift"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ec -ct 1 -cn FreqShiftDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */
#[repr(C)]
pub struct FreqShiftDsp {
	fSampleRate: i32,
	fConst0: F32,
	fConst1: F32,
	fConst2: F32,
	fConst3: F32,
	fConst4: F32,
	iVec0: [i32;2],
	fConst5: F32,
	fHslider0: F32,
	fSlow0: F32,
	fSlow1: F32,
	fRec0: [F32;2],
	fRec1: [F32;2],
	iRec2: [i32;3],
	fConst6: F32,
	fConst7: F32,
	fConst8: F32,
	fConst9: F32,
	fConst10: F32,
	fConst11: F32,
	fRec7: [F32;3],
	fConst12: F32,
	fRec6: [F32;3],
	fConst13: F32,
	fRec5: [F32;3],
	fConst14: F32,
	fRec4: [F32;3],
	fConst15: F32,
	fConst16: F32,
	fRec3: [F32;3],
	fRec12: [F32;3],
	fRec11: [F32;3],
	fRec10: [F32;3],
	fRec9: [F32;3],
	fRec8: [F32;3],
}

pub type FaustFloat = F32;
fn FreqShiftDsp_faustpower2_f(value: F32) -> F32 {
	return value * value;
}
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 1;
pub const FAUST_PASSIVES: usize = 0;


impl FreqShiftDsp {
		
	pub fn new() -> FreqShiftDsp { 
		FreqShiftDsp {
			fSampleRate: 0,
			fConst0: 0.0,
			fConst1: 0.0,
			fConst2: 0.0,
			fConst3: 0.0,
			fConst4: 0.0,
			iVec0: [0;2],
			fConst5: 0.0,
			fHslider0: 0.0,
			fSlow0: 0.0,
			fSlow1: 0.0,
			fRec0: [0.0;2],
			fRec1: [0.0;2],
			iRec2: [0;3],
			fConst6: 0.0,
			fConst7: 0.0,
			fConst8: 0.0,
			fConst9: 0.0,
			fConst10: 0.0,
			fConst11: 0.0,
			fRec7: [0.0;3],
			fConst12: 0.0,
			fRec6: [0.0;3],
			fConst13: 0.0,
			fRec5: [0.0;3],
			fConst14: 0.0,
			fRec4: [0.0;3],
			fConst15: 0.0,
			fConst16: 0.0,
			fRec3: [0.0;3],
			fRec12: [0.0;3],
			fRec11: [0.0;3],
			fRec10: [0.0;3],
			fRec9: [0.0;3],
			fRec8: [0.0;3],
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("compile_options", r"-lang rust -ec -ct 1 -cn FreqShiftDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
		m.declare("filename", r"fshift.dsp");
		m.declare("filters.lib/fir:author", r"Julius O. Smith III");
		m.declare("filters.lib/fir:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/fir:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/iir:author", r"Julius O. Smith III");
		m.declare("filters.lib/iir:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/iir:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/lowpass0_highpass1", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowpass0_highpass1:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowpass:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowpass:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowpass:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/name", r"Faust Filters Library");
		m.declare("filters.lib/pospass0:author", r"Julius O. Smith III");
		m.declare("filters.lib/pospass0:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/pospass0:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/pospass:author", r"Julius O. Smith III");
		m.declare("filters.lib/pospass:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/pospass:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf2:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf2:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf2:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf2s:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf2s:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf2s:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/version", r"1.7.1");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"fshift");
		m.declare("oscillators.lib/name", r"Faust Oscillator Library");
		m.declare("oscillators.lib/version", r"1.6.0");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.iVec0[l0 as usize] = 0;
		}
		for l1 in 0..2 {
			self.fRec0[l1 as usize] = 0.0;
		}
		for l2 in 0..2 {
			self.fRec1[l2 as usize] = 0.0;
		}
		for l3 in 0..3 {
			self.iRec2[l3 as usize] = 0;
		}
		for l4 in 0..3 {
			self.fRec7[l4 as usize] = 0.0;
		}
		for l5 in 0..3 {
			self.fRec6[l5 as usize] = 0.0;
		}
		for l6 in 0..3 {
			self.fRec5[l6 as usize] = 0.0;
		}
		for l7 in 0..3 {
			self.fRec4[l7 as usize] = 0.0;
		}
		for l8 in 0..3 {
			self.fRec3[l8 as usize] = 0.0;
		}
		for l9 in 0..3 {
			self.fRec12[l9 as usize] = 0.0;
		}
		for l10 in 0..3 {
			self.fRec11[l10 as usize] = 0.0;
		}
		for l11 in 0..3 {
			self.fRec10[l11 as usize] = 0.0;
		}
		for l12 in 0..3 {
			self.fRec9[l12 as usize] = 0.0;
		}
		for l13 in 0..3 {
			self.fRec8[l13 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = F32::tan(3.1415927 * ((0.25 * self.fConst0 + -2e+01) / self.fConst0));
		self.fConst2 = 1.0 / self.fConst1;
		self.fConst3 = (self.fConst2 + 0.31286892) / self.fConst1 + 1.0;
		self.fConst4 = 2.0 / self.fConst3;
		self.fConst5 = 3.1415927 / self.fConst0;
		self.fConst6 = 1.0 / ((self.fConst2 + 0.907981) / self.fConst1 + 1.0);
		self.fConst7 = 1.0 / ((self.fConst2 + 1.4142135) / self.fConst1 + 1.0);
		self.fConst8 = 1.0 / ((self.fConst2 + 1.782013) / self.fConst1 + 1.0);
		self.fConst9 = 1.0 / ((self.fConst2 + 1.9753767) / self.fConst1 + 1.0);
		self.fConst10 = (self.fConst2 + -1.9753767) / self.fConst1 + 1.0;
		self.fConst11 = 2.0 * (1.0 - 1.0 / FreqShiftDsp_faustpower2_f(self.fConst1));
		self.fConst12 = (self.fConst2 + -1.782013) / self.fConst1 + 1.0;
		self.fConst13 = (self.fConst2 + -1.4142135) / self.fConst1 + 1.0;
		self.fConst14 = (self.fConst2 + -0.907981) / self.fConst1 + 1.0;
		self.fConst15 = 1.0 / self.fConst3;
		self.fConst16 = (self.fConst2 + -0.31286892) / self.fConst1 + 1.0;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		FreqShiftDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("fshift");
		ui_interface.add_horizontal_slider("a_shift", ParamIndex(0), 0.0, -2e+03, 2e+03, 0.001);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			0 => Some(self.fHslider0),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			0 => { self.fHslider0 = value }
			_ => {}
		}
	}
	
	pub fn control(&mut self) {
		// Obtaining locks on 0 static var(s)
	self.fSlow0 = F32::tan(self.fConst5 * self.fHslider0);
		self.fSlow1 = 2.0 * (self.fSlow0 / (FreqShiftDsp_faustpower2_f(self.fSlow0) + 1.0));
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			self.iVec0[0] = 1;
			let mut fTemp0: F32 = self.fRec1[1] + self.fSlow1 * (self.fRec0[1] - self.fSlow0 * self.fRec1[1]);
			let mut fTemp1: F32 = (if self.iVec0[1] != 0 {self.fRec0[1] - self.fSlow0 * (self.fRec1[1] + fTemp0)} else {1.0});
			self.fRec0[0] = (if (F32::abs(fTemp1) > 1.1754944e-38) as i32 != 0 {fTemp1} else {0.0});
			self.fRec1[0] = (if (F32::abs(fTemp0) > 1.1754944e-38) as i32 != 0 {fTemp0} else {0.0});
			self.iRec2[0] = i32::wrapping_sub(1, i32::wrapping_add(self.iVec0[1], self.iRec2[2]));
			let mut fTemp2: F32 = (self.iRec2[0]) as F32;
			let mut fTemp3: F32 = *input0;
			let mut fTemp4: F32 = fTemp3 * fTemp2 - self.fConst9 * (self.fConst10 * self.fRec7[2] + self.fConst11 * self.fRec7[1]);
			self.fRec7[0] = (if (F32::abs(fTemp4) > 1.1754944e-38) as i32 != 0 {fTemp4} else {0.0});
			let mut fTemp5: F32 = self.fConst9 * (self.fRec7[2] + self.fRec7[0] + 2.0 * self.fRec7[1]) - self.fConst8 * (self.fConst12 * self.fRec6[2] + self.fConst11 * self.fRec6[1]);
			self.fRec6[0] = (if (F32::abs(fTemp5) > 1.1754944e-38) as i32 != 0 {fTemp5} else {0.0});
			let mut fTemp6: F32 = self.fConst8 * (self.fRec6[2] + self.fRec6[0] + 2.0 * self.fRec6[1]) - self.fConst7 * (self.fConst13 * self.fRec5[2] + self.fConst11 * self.fRec5[1]);
			self.fRec5[0] = (if (F32::abs(fTemp6) > 1.1754944e-38) as i32 != 0 {fTemp6} else {0.0});
			let mut fTemp7: F32 = self.fConst7 * (self.fRec5[2] + self.fRec5[0] + 2.0 * self.fRec5[1]) - self.fConst6 * (self.fConst14 * self.fRec4[2] + self.fConst11 * self.fRec4[1]);
			self.fRec4[0] = (if (F32::abs(fTemp7) > 1.1754944e-38) as i32 != 0 {fTemp7} else {0.0});
			let mut fTemp8: F32 = self.fConst6 * (self.fRec4[2] + self.fRec4[0] + 2.0 * self.fRec4[1]) - self.fConst15 * (self.fConst16 * self.fRec3[2] + self.fConst11 * self.fRec3[1]);
			self.fRec3[0] = (if (F32::abs(fTemp8) > 1.1754944e-38) as i32 != 0 {fTemp8} else {0.0});
			let mut fTemp9: F32 = self.fRec3[2] + self.fRec3[0] + 2.0 * self.fRec3[1];
			let mut fTemp10: F32 = (self.iRec2[1]) as F32;
			let mut fTemp11: F32 = fTemp3 * (-self.iRec2[1]) as F32 - self.fConst9 * (self.fConst10 * self.fRec12[2] + self.fConst11 * self.fRec12[1]);
			self.fRec12[0] = (if (F32::abs(fTemp11) > 1.1754944e-38) as i32 != 0 {fTemp11} else {0.0});
			let mut fTemp12: F32 = self.fConst9 * (self.fRec12[2] + self.fRec12[0] + 2.0 * self.fRec12[1]) - self.fConst8 * (self.fConst12 * self.fRec11[2] + self.fConst11 * self.fRec11[1]);
			self.fRec11[0] = (if (F32::abs(fTemp12) > 1.1754944e-38) as i32 != 0 {fTemp12} else {0.0});
			let mut fTemp13: F32 = self.fConst8 * (self.fRec11[2] + self.fRec11[0] + 2.0 * self.fRec11[1]) - self.fConst7 * (self.fConst13 * self.fRec10[2] + self.fConst11 * self.fRec10[1]);
			self.fRec10[0] = (if (F32::abs(fTemp13) > 1.1754944e-38) as i32 != 0 {fTemp13} else {0.0});
			let mut fTemp14: F32 = self.fConst7 * (self.fRec10[2] + self.fRec10[0] + 2.0 * self.fRec10[1]) - self.fConst6 * (self.fConst14 * self.fRec9[2] + self.fConst11 * self.fRec9[1]);
			self.fRec9[0] = (if (F32::abs(fTemp14) > 1.1754944e-38) as i32 != 0 {fTemp14} else {0.0});
			let mut fTemp15: F32 = self.fConst6 * (self.fRec9[2] + self.fRec9[0] + 2.0 * self.fRec9[1]) - self.fConst15 * (self.fConst16 * self.fRec8[2] + self.fConst11 * self.fRec8[1]);
			self.fRec8[0] = (if (F32::abs(fTemp15) > 1.1754944e-38) as i32 != 0 {fTemp15} else {0.0});
			let mut fTemp16: F32 = self.fRec8[2] + self.fRec8[0] + 2.0 * self.fRec8[1];
			*output0 = self.fConst4 * (self.fRec0[0] * (fTemp2 * fTemp9 - fTemp10 * fTemp16) - self.fRec1[0] * (fTemp2 * fTemp16 + fTemp9 * fTemp10));
			self.iVec0[1] = self.iVec0[0];
			self.fRec0[1] = self.fRec0[0];
			self.fRec1[1] = self.fRec1[0];
			self.iRec2[2] = self.iRec2[1];
			self.iRec2[1] = self.iRec2[0];
			self.fRec7[2] = self.fRec7[1];
			self.fRec7[1] = self.fRec7[0];
			self.fRec6[2] = self.fRec6[1];
			self.fRec6[1] = self.fRec6[0];
			self.fRec5[2] = self.fRec5[1];
			self.fRec5[1] = self.fRec5[0];
			self.fRec4[2] = self.fRec4[1];
			self.fRec4[1] = self.fRec4[0];
			self.fRec3[2] = self.fRec3[1];
			self.fRec3[1] = self.fRec3[0];
			self.fRec12[2] = self.fRec12[1];
			self.fRec12[1] = self.fRec12[0];
			self.fRec11[2] = self.fRec11[1];
			self.fRec11[1] = self.fRec11[0];
			self.fRec10[2] = self.fRec10[1];
			self.fRec10[1] = self.fRec10[0];
			self.fRec9[2] = self.fRec9[1];
			self.fRec9[1] = self.fRec9[0];
			self.fRec8[2] = self.fRec8[1];
			self.fRec8[1] = self.fRec8[0];
		}
		
	}

}

impl FaustDsp for FreqShiftDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
