// @generated by dsp/regen.sh from dsp/haas.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "haas"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ec -ct 1 -cn HaasDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */
#[repr(C)]
pub struct HaasDsp {
	fSampleRate: i32,
	fConst0: F32,
	fHslider0: F32,
	fSlow0: F32,
	fSlow1: F32,
	fSlow2: F32,
	fSlow3: F32,
	fSlow4: F32,
	fSlow5: F32,
	fSlow6: F32,
	fSlow7: F32,
	IOTA0: i32,
	fVec0: [F32;8192],
	iSlow8: i32,
	iSlow9: i32,
	fSlow10: F32,
	fSlow11: F32,
	iSlow12: i32,
	fSlow13: F32,
	fSlow14: F32,
	iSlow15: i32,
	fSlow16: F32,
	fSlow17: F32,
	iSlow18: i32,
	fSlow19: F32,
	iSlow20: i32,
}

pub type FaustFloat = F32;
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 1;
pub const FAUST_PASSIVES: usize = 0;


impl HaasDsp {
		
	pub fn new() -> HaasDsp { 
		HaasDsp {
			fSampleRate: 0,
			fConst0: 0.0,
			fHslider0: 0.0,
			fSlow0: 0.0,
			fSlow1: 0.0,
			fSlow2: 0.0,
			fSlow3: 0.0,
			fSlow4: 0.0,
			fSlow5: 0.0,
			fSlow6: 0.0,
			fSlow7: 0.0,
			IOTA0: 0,
			fVec0: [0.0;8192],
			iSlow8: 0,
			iSlow9: 0,
			fSlow10: 0.0,
			fSlow11: 0.0,
			iSlow12: 0,
			fSlow13: 0.0,
			fSlow14: 0.0,
			iSlow15: 0,
			fSlow16: 0.0,
			fSlow17: 0.0,
			iSlow18: 0,
			fSlow19: 0.0,
			iSlow20: 0,
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("compile_options", r"-lang rust -ec -ct 1 -cn HaasDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0");
		m.declare("delays.lib/fdelay4:author", r"Julius O. Smith III");
		m.declare("delays.lib/fdelayltv:author", r"Julius O. Smith III");
		m.declare("delays.lib/name", r"Faust Delay Library");
		m.declare("delays.lib/version", r"1.2.0");
		m.declare("filename", r"haas.dsp");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"haas");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		self.IOTA0 = 0;
		for l0 in 0..8192 {
			self.fVec0[l0 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = 0.001 * F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		HaasDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("haas");
		ui_interface.add_horizontal_slider("a_ms", ParamIndex(0), 0.0, 0.0, 5e+01, 0.001);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			0 => Some(self.fHslider0),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			0 => { self.fHslider0 = value }
			_ => {}
		}
	}
	
	pub fn control(&mut self) {
		// Obtaining locks on 0 static var(s)
	self.fSlow0 = F32::max(2.0, F32::min(8189.0, self.fConst0 * self.fHslider0));
		self.fSlow1 = self.fSlow0 + -1.499995;
		self.fSlow2 = F32::floor(self.fSlow1);
		self.fSlow3 = self.fSlow0 + (-4.0 - self.fSlow2);
		self.fSlow4 = self.fSlow0 + (-3.0 - self.fSlow2);
		self.fSlow5 = self.fSlow0 + (-2.0 - self.fSlow2);
		self.fSlow6 = self.fSlow0 + (-1.0 - self.fSlow2);
		self.fSlow7 = 0.041666668 * self.fSlow6;
		self.iSlow8 = (self.fSlow1) as i32;
		self.iSlow9 = std::cmp::min(8192, std::cmp::max(0, self.iSlow8));
		self.fSlow10 = self.fSlow0 - self.fSlow2;
		self.fSlow11 = 0.16666667 * self.fSlow10;
		self.iSlow12 = std::cmp::min(8192, std::cmp::max(0, i32::wrapping_add(self.iSlow8, 1)));
		self.fSlow13 = self.fSlow10 * self.fSlow6;
		self.fSlow14 = 0.25 * self.fSlow13;
		self.iSlow15 = std::cmp::min(8192, std::cmp::max(0, i32::wrapping_add(self.iSlow8, 2)));
		self.fSlow16 = self.fSlow13 * self.fSlow5;
		self.fSlow17 = 0.16666667 * self.fSlow16;
		self.iSlow18 = std::cmp::min(8192, std::cmp::max(0, i32::wrapping_add(self.iSlow8, 3)));
		self.fSlow19 = 0.041666668 * self.fSlow16 * self.fSlow4;
		self.iSlow20 = std::cmp::min(8192, std::cmp::max(0, i32::wrapping_add(self.iSlow8, 4)));
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = *input0;
			self.fVec0[(self.IOTA0 & 8191) as usize] = fTemp0;
			*output0 = self.fSlow3 * (self.fSlow4 * (self.fSlow5 * (self.fSlow7 * self.fVec0[((i32::wrapping_sub(self.IOTA0, self.iSlow9)) & 8191) as usize] - self.fSlow11 * self.fVec0[((i32::wrapping_sub(self.IOTA0, self.iSlow12)) & 8191) as usize]) + self.fSlow14 * self.fVec0[((i32::wrapping_sub(self.IOTA0, self.iSlow15)) & 8191) as usize]) - self.fSlow17 * self.fVec0[((i32::wrapping_sub(self.IOTA0, self.iSlow18)) & 8191) as usize]) + self.fSlow19 * self.fVec0[((i32::wrapping_sub(self.IOTA0, self.iSlow20)) & 8191) as usize];
			self.IOTA0 = i32::wrapping_add(self.IOTA0, 1);
		}
		
	}

}

impl FaustDsp for HaasDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
