// @generated by dsp/regen.sh from dsp/pshift.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "pshift"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ct 1 -cn PitchShiftDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */
#[repr(C)]
pub struct PitchShiftDsp {
	IOTA0: i32,
	fVec0: [F32;131072],
	fSampleRate: i32,
	fConst0: F32,
	fConst1: F32,
	fHslider0: F32,
	fHslider1: F32,
	fRec0: [F32;2],
	fConst2: F32,
}

pub type FaustFloat = F32;
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 2;
pub const FAUST_PASSIVES: usize = 0;


impl PitchShiftDsp {
		
	pub fn new() -> PitchShiftDsp { 
		PitchShiftDsp {
			IOTA0: 0,
			fVec0: [0.0;131072],
			fSampleRate: 0,
			fConst0: 0.0,
			fConst1: 0.0,
			fHslider0: 0.0,
			fHslider1: 0.0,
			fRec0: [0.0;2],
			fConst2: 0.0,
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("compile_options", r"-lang rust -ct 1 -cn PitchShiftDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0");
		m.declare("delays.lib/name", r"Faust Delay Library");
		m.declare("delays.lib/version", r"1.2.0");
		m.declare("filename", r"pshift.dsp");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("misceffects.lib/name", r"Misc Effects Library");
		m.declare("misceffects.lib/version", r"2.5.1");
		m.declare("name", r"pshift");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 4e+01;
		self.fHslider1 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		self.IOTA0 = 0;
		for l0 in 0..131072 {
			self.fVec0[l0 as usize] = 0.0;
		}
		for l1 in 0..2 {
			self.fRec0[l1 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = 0.001 * self.fConst0;
		self.fConst2 = 4e+03 / self.fConst0;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		PitchShiftDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("pshift");
		ui_interface.add_horizontal_slider("a_shift", ParamIndex(0), 0.0, -24.0, 24.0, 0.001);
		ui_interface.add_horizontal_slider("b_window", ParamIndex(1), 4e+01, 5.0, 2e+02, 0.01);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			1 => Some(self.fHslider0),
			0 => Some(self.fHslider1),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			1 => { self.fHslider0 = value }
			0 => { self.fHslider1 = value }
			_ => {}
		}
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let mut fSlow0: F32 = self.fHslider0;
		let mut fSlow1: F32 = self.fConst1 * fSlow0;
		let mut fSlow2: F32 = F32::powf(2.0, 0.083333336 * self.fHslider1);
		let mut fSlow3: F32 = self.fConst2 / fSlow0;
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = *input0;
			self.fVec0[(self.IOTA0 & 131071) as usize] = fTemp0;
			self.fRec0[0] = (fSlow1 + (self.fRec0[1] + 1.0 - fSlow2)) % fSlow1;
			let mut iTemp1: i32 = (self.fRec0[0]) as i32;
			let mut fTemp2: F32 = F32::floor(self.fRec0[0]);
			let mut fTemp3: F32 = 1.0 - self.fRec0[0];
			let mut fTemp4: F32 = F32::min(fSlow3 * self.fRec0[0], 1.0);
			let mut fTemp5: F32 = fSlow1 + self.fRec0[0];
			let mut iTemp6: i32 = (fTemp5) as i32;
			let mut fTemp7: F32 = F32::floor(fTemp5);
			*output0 = (self.fVec0[((i32::wrapping_sub(self.IOTA0, std::cmp::min(65537, std::cmp::max(0, iTemp1)))) & 131071) as usize] * (fTemp2 + fTemp3) + (self.fRec0[0] - fTemp2) * self.fVec0[((i32::wrapping_sub(self.IOTA0, std::cmp::min(65537, std::cmp::max(0, i32::wrapping_add(iTemp1, 1))))) & 131071) as usize]) * fTemp4 + (self.fVec0[((i32::wrapping_sub(self.IOTA0, std::cmp::min(65537, std::cmp::max(0, iTemp6)))) & 131071) as usize] * (fTemp7 + fTemp3 - fSlow1) + (fSlow1 + (self.fRec0[0] - fTemp7)) * self.fVec0[((i32::wrapping_sub(self.IOTA0, std::cmp::min(65537, std::cmp::max(0, i32::wrapping_add(iTemp6, 1))))) & 131071) as usize]) * (1.0 - fTemp4);
			self.IOTA0 = i32::wrapping_add(self.IOTA0, 1);
			self.fRec0[1] = self.fRec0[0];
		}
		
	}

}

impl FaustDsp for PitchShiftDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
