// @generated by dsp/regen.sh from dsp/smear.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "smear"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ec -ct 1 -cn SmearDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */
#[repr(C)]
pub struct SmearDsp {
	fHslider0: F32,
	fSlow0: F32,
	fSlow1: F32,
	fHslider1: F32,
	fSlow2: F32,
	fVec0: [F32;2],
	fSampleRate: i32,
	fConst0: F32,
	fConst1: F32,
	fHslider2: F32,
	fConst2: F32,
	fSlow3: F32,
	fSlow4: F32,
	fRec12: [F32;2],
	fRec11: [F32;2],
	fRec10: [F32;2],
	fRec9: [F32;2],
	fRec8: [F32;2],
	fRec7: [F32;2],
	fRec6: [F32;2],
	fRec5: [F32;2],
	fRec4: [F32;2],
	fRec3: [F32;2],
	fRec2: [F32;2],
	fRec1: [F32;2],
	fRec0: [F32;2],
}

pub type FaustFloat = F32;
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 3;
pub const FAUST_PASSIVES: usize = 0;


impl SmearDsp {
		
	pub fn new() -> SmearDsp { 
		SmearDsp {
			fHslider0: 0.0,
			fSlow0: 0.0,
			fSlow1: 0.0,
			fHslider1: 0.0,
			fSlow2: 0.0,
			fVec0: [0.0;2],
			fSampleRate: 0,
			fConst0: 0.0,
			fConst1: 0.0,
			fHslider2: 0.0,
			fConst2: 0.0,
			fSlow3: 0.0,
			fSlow4: 0.0,
			fRec12: [0.0;2],
			fRec11: [0.0;2],
			fRec10: [0.0;2],
			fRec9: [0.0;2],
			fRec8: [0.0;2],
			fRec7: [0.0;2],
			fRec6: [0.0;2],
			fRec5: [0.0;2],
			fRec4: [0.0;2],
			fRec3: [0.0;2],
			fRec2: [0.0;2],
			fRec1: [0.0;2],
			fRec0: [0.0;2],
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("compile_options", r"-lang rust -ec -ct 1 -cn SmearDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
		m.declare("filename", r"smear.dsp");
		m.declare("filters.lib/lowpass0_highpass1", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/name", r"Faust Filters Library");
		m.declare("filters.lib/tf1:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf1:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf1:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/version", r"1.7.1");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"smear");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 0.0;
		self.fHslider1 = 0.0;
		self.fHslider2 = 1e+03;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.fVec0[l0 as usize] = 0.0;
		}
		for l1 in 0..2 {
			self.fRec12[l1 as usize] = 0.0;
		}
		for l2 in 0..2 {
			self.fRec11[l2 as usize] = 0.0;
		}
		for l3 in 0..2 {
			self.fRec10[l3 as usize] = 0.0;
		}
		for l4 in 0..2 {
			self.fRec9[l4 as usize] = 0.0;
		}
		for l5 in 0..2 {
			self.fRec8[l5 as usize] = 0.0;
		}
		for l6 in 0..2 {
			self.fRec7[l6 as usize] = 0.0;
		}
		for l7 in 0..2 {
			self.fRec6[l7 as usize] = 0.0;
		}
		for l8 in 0..2 {
			self.fRec5[l8 as usize] = 0.0;
		}
		for l9 in 0..2 {
			self.fRec4[l9 as usize] = 0.0;
		}
		for l10 in 0..2 {
			self.fRec3[l10 as usize] = 0.0;
		}
		for l11 in 0..2 {
			self.fRec2[l11 as usize] = 0.0;
		}
		for l12 in 0..2 {
			self.fRec1[l12 as usize] = 0.0;
		}
		for l13 in 0..2 {
			self.fRec0[l13 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = 3.1415927 / self.fConst0;
		self.fConst2 = 0.4999 * self.fConst0;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		SmearDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("smear");
		ui_interface.add_horizontal_slider("a_mix", ParamIndex(0), 0.0, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("b_freq", ParamIndex(1), 1e+03, 2e+01, 2e+04, 0.001);
		ui_interface.add_horizontal_slider("c_fb", ParamIndex(2), 0.0, 0.0, 0.95, 0.001);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			0 => Some(self.fHslider0),
			2 => Some(self.fHslider1),
			1 => Some(self.fHslider2),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			0 => { self.fHslider0 = value }
			2 => { self.fHslider1 = value }
			1 => { self.fHslider2 = value }
			_ => {}
		}
	}
	
	pub fn control(&mut self) {
		// Obtaining locks on 0 static var(s)
	self.fSlow0 = self.fHslider0;
		self.fSlow1 = 1.0 - self.fSlow0;
		self.fSlow2 = F32::max(0.0, F32::min(0.95, self.fHslider1));
		self.fSlow3 = F32::tan(self.fConst1 * F32::max(1.0, F32::min(self.fHslider2, self.fConst2)));
		self.fSlow4 = (self.fSlow3 + -1.0) / (self.fSlow3 + 1.0);
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = *input0;
			let mut fTemp1: F32 = fTemp0 + self.fSlow2 * self.fRec0[1];
			self.fVec0[0] = fTemp1;
			let mut fTemp2: F32 = self.fVec0[1] - self.fSlow4 * (self.fRec12[1] - fTemp1);
			self.fRec12[0] = (if (F32::abs(fTemp2) > 1.1754944e-38) as i32 != 0 {fTemp2} else {0.0});
			let mut fTemp3: F32 = self.fRec12[1] - self.fSlow4 * (self.fRec11[1] - self.fRec12[0]);
			self.fRec11[0] = (if (F32::abs(fTemp3) > 1.1754944e-38) as i32 != 0 {fTemp3} else {0.0});
			let mut fTemp4: F32 = self.fRec11[1] - self.fSlow4 * (self.fRec10[1] - self.fRec11[0]);
			self.fRec10[0] = (if (F32::abs(fTemp4) > 1.1754944e-38) as i32 != 0 {fTemp4} else {0.0});
			let mut fTemp5: F32 = self.fRec10[1] - self.fSlow4 * (self.fRec9[1] - self.fRec10[0]);
			self.fRec9[0] = (if (F32::abs(fTemp5) > 1.1754944e-38) as i32 != 0 {fTemp5} else {0.0});
			let mut fTemp6: F32 = self.fRec9[1] - self.fSlow4 * (self.fRec8[1] - self.fRec9[0]);
			self.fRec8[0] = (if (F32::abs(fTemp6) > 1.1754944e-38) as i32 != 0 {fTemp6} else {0.0});
			let mut fTemp7: F32 = self.fRec8[1] - self.fSlow4 * (self.fRec7[1] - self.fRec8[0]);
			self.fRec7[0] = (if (F32::abs(fTemp7) > 1.1754944e-38) as i32 != 0 {fTemp7} else {0.0});
			let mut fTemp8: F32 = self.fRec7[1] - self.fSlow4 * (self.fRec6[1] - self.fRec7[0]);
			self.fRec6[0] = (if (F32::abs(fTemp8) > 1.1754944e-38) as i32 != 0 {fTemp8} else {0.0});
			let mut fTemp9: F32 = self.fRec6[1] - self.fSlow4 * (self.fRec5[1] - self.fRec6[0]);
			self.fRec5[0] = (if (F32::abs(fTemp9) > 1.1754944e-38) as i32 != 0 {fTemp9} else {0.0});
			let mut fTemp10: F32 = self.fRec5[1] - self.fSlow4 * (self.fRec4[1] - self.fRec5[0]);
			self.fRec4[0] = (if (F32::abs(fTemp10) > 1.1754944e-38) as i32 != 0 {fTemp10} else {0.0});
			let mut fTemp11: F32 = self.fRec4[1] - self.fSlow4 * (self.fRec3[1] - self.fRec4[0]);
			self.fRec3[0] = (if (F32::abs(fTemp11) > 1.1754944e-38) as i32 != 0 {fTemp11} else {0.0});
			let mut fTemp12: F32 = self.fRec3[1] - self.fSlow4 * (self.fRec2[1] - self.fRec3[0]);
			self.fRec2[0] = (if (F32::abs(fTemp12) > 1.1754944e-38) as i32 != 0 {fTemp12} else {0.0});
			let mut fTemp13: F32 = self.fRec2[1] - self.fSlow4 * (self.fRec1[1] - self.fRec2[0]);
			self.fRec1[0] = (if (F32::abs(fTemp13) > 1.1754944e-38) as i32 != 0 {fTemp13} else {0.0});
			self.fRec0[0] = (if (F32::abs(self.fRec1[0]) > 1.1754944e-38) as i32 != 0 {self.fRec1[0]} else {0.0});
			*output0 = self.fSlow1 * fTemp0 + self.fSlow0 * self.fRec0[0];
			self.fVec0[1] = self.fVec0[0];
			self.fRec12[1] = self.fRec12[0];
			self.fRec11[1] = self.fRec11[0];
			self.fRec10[1] = self.fRec10[0];
			self.fRec9[1] = self.fRec9[0];
			self.fRec8[1] = self.fRec8[0];
			self.fRec7[1] = self.fRec7[0];
			self.fRec6[1] = self.fRec6[0];
			self.fRec5[1] = self.fRec5[0];
			self.fRec4[1] = self.fRec4[0];
			self.fRec3[1] = self.fRec3[0];
			self.fRec2[1] = self.fRec2[0];
			self.fRec1[1] = self.fRec1[0];
			self.fRec0[1] = self.fRec0[0];
		}
		
	}

}

impl FaustDsp for SmearDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
