// @generated by dsp/regen.sh from dsp/svf24.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "svf24"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ct 1 -cn Svf24Dsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */
#[repr(C)]
pub struct Svf24Dsp {
	fHslider0: F32,
	fSampleRate: i32,
	fConst0: F32,
	fConst1: F32,
	fHslider1: F32,
	fConst2: F32,
	fHslider2: F32,
	fRec5: [F32;2],
	fRec6: [F32;2],
	fRec0: [F32;2],
	fRec1: [F32;2],
}

pub type FaustFloat = F32;
fn Svf24Dsp_faustpower2_f(value: F32) -> F32 {
	return value * value;
}
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 3;
pub const FAUST_PASSIVES: usize = 0;


impl Svf24Dsp {
		
	pub fn new() -> Svf24Dsp { 
		Svf24Dsp {
			fHslider0: 0.0,
			fSampleRate: 0,
			fConst0: 0.0,
			fConst1: 0.0,
			fHslider1: 0.0,
			fConst2: 0.0,
			fHslider2: 0.0,
			fRec5: [0.0;2],
			fRec6: [0.0;2],
			fRec0: [0.0;2],
			fRec1: [0.0;2],
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("compile_options", r"-lang rust -ct 1 -cn Svf24Dsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
		m.declare("filename", r"svf24.dsp");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"svf24");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
		m.declare("signals.lib/name", r"Faust Signal Routing Library");
		m.declare("signals.lib/version", r"1.6.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 0.0;
		self.fHslider1 = 1e+03;
		self.fHslider2 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.fRec5[l0 as usize] = 0.0;
		}
		for l1 in 0..2 {
			self.fRec6[l1 as usize] = 0.0;
		}
		for l2 in 0..2 {
			self.fRec0[l2 as usize] = 0.0;
		}
		for l3 in 0..2 {
			self.fRec1[l3 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = 3.1415927 / self.fConst0;
		self.fConst2 = 0.45 * self.fConst0;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		Svf24Dsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("svf24");
		ui_interface.add_horizontal_slider("a_cutoff", ParamIndex(0), 1e+03, 1.0, 2e+04, 0.001);
		ui_interface.add_horizontal_slider("b_q", ParamIndex(1), 0.0, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("c_mode", ParamIndex(2), 0.0, 0.0, 2.0, 1.0);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			2 => Some(self.fHslider0),
			0 => Some(self.fHslider1),
			1 => Some(self.fHslider2),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			2 => { self.fHslider0 = value }
			0 => { self.fHslider1 = value }
			1 => { self.fHslider2 = value }
			_ => {}
		}
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let mut iSlow0: i32 = (self.fHslider0) as i32;
		let mut iSlow1: i32 = (iSlow0 == 0) as i32;
		let mut iSlow2: i32 = (iSlow0 == 1) as i32;
		let mut fSlow3: F32 = F32::tan(self.fConst1 * F32::max(1.0, F32::min(self.fHslider1, self.fConst2)));
		let mut fSlow4: F32 = fSlow3 * (fSlow3 + 1.4711188) + 1.0;
		let mut fSlow5: F32 = 1.0 / fSlow4;
		let mut fSlow6: F32 = F32::max(0.0, F32::min(1.0, self.fHslider2));
		let mut fSlow7: F32 = 1.0 / (29.5 * Svf24Dsp_faustpower2_f(fSlow6) * F32::sqrt(fSlow6) + 0.5);
		let mut fSlow8: F32 = fSlow3 * (fSlow7 + fSlow3) + 1.0;
		let mut fSlow9: F32 = 1.0 / fSlow8;
		let mut fSlow10: F32 = 1.0 - 0.5 * fSlow6;
		let mut fSlow11: F32 = fSlow3 / fSlow8;
		let mut fSlow12: F32 = fSlow3 / fSlow4;
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = fSlow10 * *input0;
			let mut fTemp1: F32 = self.fRec5[1] + fSlow3 * (fTemp0 - self.fRec6[1]);
			let mut fTemp2: F32 = F32::max(-3.0, F32::min(3.0, fSlow9 * fTemp1));
			let mut fTemp3: F32 = Svf24Dsp_faustpower2_f(fTemp2);
			let mut fTemp4: F32 = fTemp2 * (fTemp3 + 27.0) / (9.0 * fTemp3 + 27.0);
			let mut fTemp5: F32 = 2.0 * fTemp4 - self.fRec5[1];
			self.fRec5[0] = (if (F32::abs(fTemp5) > 1.1754944e-38) as i32 != 0 {fTemp5} else {0.0});
			let mut fTemp6: F32 = self.fRec6[1] + fSlow11 * fTemp1;
			let mut fTemp7: F32 = 2.0 * fTemp6 - self.fRec6[1];
			self.fRec6[0] = (if (F32::abs(fTemp7) > 1.1754944e-38) as i32 != 0 {fTemp7} else {0.0});
			let mut fRec7: F32 = (if (F32::abs(fTemp6) > 1.1754944e-38) as i32 != 0 {fTemp6} else {0.0});
			let mut fTemp8: F32 = fTemp0 - (fTemp6 + fSlow7 * fTemp4);
			let mut fRec8: F32 = (if (F32::abs(fTemp8) > 1.1754944e-38) as i32 != 0 {fTemp8} else {0.0});
			let mut fRec9: F32 = (if (F32::abs(fTemp4) > 1.1754944e-38) as i32 != 0 {fTemp4} else {0.0});
			let mut fTemp9: F32 = 0.935 * (if iSlow1 != 0 {fRec7} else {(if iSlow2 != 0 {fRec8} else {fRec9})});
			let mut fTemp10: F32 = self.fRec0[1] + fSlow3 * (fTemp9 - self.fRec1[1]);
			let mut fTemp11: F32 = F32::max(-3.0, F32::min(3.0, fSlow5 * fTemp10));
			let mut fTemp12: F32 = Svf24Dsp_faustpower2_f(fTemp11);
			let mut fTemp13: F32 = fTemp11 * (fTemp12 + 27.0) / (9.0 * fTemp12 + 27.0);
			let mut fTemp14: F32 = 2.0 * fTemp13 - self.fRec0[1];
			self.fRec0[0] = (if (F32::abs(fTemp14) > 1.1754944e-38) as i32 != 0 {fTemp14} else {0.0});
			let mut fTemp15: F32 = fSlow12 * fTemp10;
			let mut fTemp16: F32 = self.fRec1[1] + fTemp15;
			let mut fTemp17: F32 = 2.0 * fTemp16 - self.fRec1[1];
			self.fRec1[0] = (if (F32::abs(fTemp17) > 1.1754944e-38) as i32 != 0 {fTemp17} else {0.0});
			let mut fRec2: F32 = (if (F32::abs(fTemp16) > 1.1754944e-38) as i32 != 0 {fTemp16} else {0.0});
			let mut fTemp18: F32 = fTemp9 - (fTemp15 + self.fRec1[1] + 1.4711188 * fTemp13);
			let mut fRec3: F32 = (if (F32::abs(fTemp18) > 1.1754944e-38) as i32 != 0 {fTemp18} else {0.0});
			let mut fRec4: F32 = (if (F32::abs(fTemp13) > 1.1754944e-38) as i32 != 0 {fTemp13} else {0.0});
			*output0 = (if iSlow1 != 0 {fRec2} else {(if iSlow2 != 0 {fRec3} else {fRec4})});
			self.fRec5[1] = self.fRec5[0];
			self.fRec6[1] = self.fRec6[0];
			self.fRec0[1] = self.fRec0[0];
			self.fRec1[1] = self.fRec1[0];
		}
		
	}

}

impl FaustDsp for Svf24Dsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
