// @generated by dsp/regen.sh from dsp/vital_rev.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "vital_rev"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ec -ct 1 -cn VitalRevDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */
#[repr(C)]
pub struct VitalRevDsp {
	fSampleRate: i32,
	fConst0: F32,
	fHslider0: F32,
	fSlow0: F32,
	fSlow1: F32,
	fHslider1: F32,
	fSlow2: F32,
	iVec0: [i32;2],
	fConst1: F32,
	fHslider2: F32,
	fSlow3: F32,
	fRec18: [F32;2],
	fHslider3: F32,
	fSlow4: F32,
	fSlow5: F32,
	fConst2: F32,
	fHslider4: F32,
	fSlow6: F32,
	fSlow7: F32,
	fSlow8: F32,
	fHslider5: F32,
	fSlow9: F32,
	fSlow10: F32,
	fSlow11: F32,
	fRec20: [F32;2],
	fHslider6: F32,
	fSlow12: F32,
	fRec21: [F32;2],
	fVec1: [F32;2],
	fRec19: [F32;2],
	fHslider7: F32,
	fSlow13: F32,
	fRec22: [F32;2],
	IOTA0: i32,
	fVec2: [F32;131072],
	fConst3: F32,
	fHslider8: F32,
	fSlow14: F32,
	fSlow15: F32,
	fSlow16: F32,
	fHslider9: F32,
	fSlow17: F32,
	fSlow18: F32,
	fSlow19: F32,
	fConst4: F32,
	fHslider10: F32,
	fSlow20: F32,
	fSlow21: F32,
	fSlow22: F32,
	fSlow23: F32,
	fSlow24: F32,
	fSlow25: F32,
	fSlow26: F32,
	fVec3: [F32;65536],
	iSlow27: i32,
	iSlow28: i32,
	fSlow29: F32,
	fSlow30: F32,
	iSlow31: i32,
	fSlow32: F32,
	fSlow33: F32,
	iSlow34: i32,
	fSlow35: F32,
	iSlow36: i32,
	fVec4: [F32;2],
	fRec24: [F32;2],
	fRec23: [F32;2],
	fVec5: [F32;1024],
	fRec16: [F32;2],
	fRec27: [F32;2],
	fSlow37: F32,
	fRec29: [F32;2],
	fRec30: [F32;2],
	fVec6: [F32;2],
	fRec28: [F32;2],
	fRec31: [F32;2],
	fVec7: [F32;131072],
	fVec8: [F32;65536],
	fVec9: [F32;2],
	fRec33: [F32;2],
	fRec32: [F32;2],
	fVec10: [F32;1024],
	fRec25: [F32;2],
	fSlow38: F32,
	fRec37: [F32;2],
	fRec38: [F32;2],
	fVec11: [F32;2],
	fRec36: [F32;2],
	fRec39: [F32;2],
	fVec12: [F32;131072],
	fVec13: [F32;1024],
	fRec34: [F32;2],
	fRec42: [F32;2],
	fSlow39: F32,
	fRec44: [F32;2],
	fRec45: [F32;2],
	fVec14: [F32;2],
	fRec43: [F32;2],
	fRec46: [F32;2],
	fVec15: [F32;131072],
	fVec16: [F32;1024],
	fRec40: [F32;2],
	fSlow40: F32,
	fRec50: [F32;2],
	fRec51: [F32;2],
	fVec17: [F32;2],
	fRec49: [F32;2],
	fRec52: [F32;2],
	fVec18: [F32;131072],
	fVec19: [F32;1024],
	fRec47: [F32;2],
	fRec55: [F32;2],
	fSlow41: F32,
	fRec57: [F32;2],
	fRec58: [F32;2],
	fVec20: [F32;2],
	fRec56: [F32;2],
	fRec59: [F32;2],
	fVec21: [F32;131072],
	fVec22: [F32;1024],
	fRec53: [F32;2],
	fSlow42: F32,
	fRec63: [F32;2],
	fRec64: [F32;2],
	fVec23: [F32;2],
	fRec62: [F32;2],
	fRec65: [F32;2],
	fVec24: [F32;65536],
	fVec25: [F32;1024],
	fRec60: [F32;2],
	fRec68: [F32;2],
	fSlow43: F32,
	fRec70: [F32;2],
	fRec71: [F32;2],
	fVec26: [F32;2],
	fRec69: [F32;2],
	fRec72: [F32;2],
	fVec27: [F32;131072],
	fVec28: [F32;1024],
	fRec66: [F32;2],
	fSlow44: F32,
	fRec76: [F32;2],
	fRec77: [F32;2],
	fVec29: [F32;2],
	fRec75: [F32;2],
	fRec78: [F32;2],
	fVec30: [F32;131072],
	fVec31: [F32;1024],
	fRec73: [F32;2],
	fRec81: [F32;2],
	fSlow45: F32,
	fRec83: [F32;2],
	fRec84: [F32;2],
	fVec32: [F32;2],
	fRec82: [F32;2],
	fRec85: [F32;2],
	fVec33: [F32;131072],
	fVec34: [F32;1024],
	fRec79: [F32;2],
	fSlow46: F32,
	fRec89: [F32;2],
	fRec90: [F32;2],
	fVec35: [F32;2],
	fRec88: [F32;2],
	fRec91: [F32;2],
	fVec36: [F32;65536],
	fVec37: [F32;1024],
	fRec86: [F32;2],
	fRec94: [F32;2],
	fSlow47: F32,
	fRec96: [F32;2],
	fRec97: [F32;2],
	fVec38: [F32;2],
	fRec95: [F32;2],
	fRec98: [F32;2],
	fVec39: [F32;131072],
	fVec40: [F32;1024],
	fRec92: [F32;2],
	fSlow48: F32,
	fRec102: [F32;2],
	fRec103: [F32;2],
	fVec41: [F32;2],
	fRec101: [F32;2],
	fRec104: [F32;2],
	fVec42: [F32;131072],
	fVec43: [F32;1024],
	fRec99: [F32;2],
	fRec107: [F32;2],
	fSlow49: F32,
	fRec109: [F32;2],
	fRec110: [F32;2],
	fVec44: [F32;2],
	fRec108: [F32;2],
	fRec111: [F32;2],
	fVec45: [F32;65536],
	fVec46: [F32;1024],
	fRec105: [F32;2],
	fSlow50: F32,
	fRec115: [F32;2],
	fRec116: [F32;2],
	fVec47: [F32;2],
	fRec114: [F32;2],
	fRec117: [F32;2],
	fVec48: [F32;65536],
	fVec49: [F32;1024],
	fRec112: [F32;2],
	fSlow51: F32,
	fRec121: [F32;2],
	fRec122: [F32;2],
	fVec50: [F32;2],
	fRec120: [F32;2],
	fRec123: [F32;2],
	fVec51: [F32;131072],
	fVec52: [F32;1024],
	fRec118: [F32;2],
	fRec0: [F32;3],
	fRec1: [F32;3],
	fRec2: [F32;3],
	fRec3: [F32;3],
	fRec4: [F32;3],
	fRec5: [F32;3],
	fRec6: [F32;3],
	fRec7: [F32;3],
	fRec8: [F32;3],
	fRec9: [F32;3],
	fRec10: [F32;3],
	fRec11: [F32;3],
	fRec12: [F32;3],
	fRec13: [F32;3],
	fRec14: [F32;3],
	fRec15: [F32;3],
}

pub type FaustFloat = F32;
fn VitalRevDsp_faustpower2_f(value: F32) -> F32 {
	return value * value;
}
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 2;
pub const FAUST_OUTPUTS: usize = 2;
pub const FAUST_ACTIVES: usize = 11;
pub const FAUST_PASSIVES: usize = 0;


impl VitalRevDsp {
		
	pub fn new() -> VitalRevDsp { 
		VitalRevDsp {
			fSampleRate: 0,
			fConst0: 0.0,
			fHslider0: 0.0,
			fSlow0: 0.0,
			fSlow1: 0.0,
			fHslider1: 0.0,
			fSlow2: 0.0,
			iVec0: [0;2],
			fConst1: 0.0,
			fHslider2: 0.0,
			fSlow3: 0.0,
			fRec18: [0.0;2],
			fHslider3: 0.0,
			fSlow4: 0.0,
			fSlow5: 0.0,
			fConst2: 0.0,
			fHslider4: 0.0,
			fSlow6: 0.0,
			fSlow7: 0.0,
			fSlow8: 0.0,
			fHslider5: 0.0,
			fSlow9: 0.0,
			fSlow10: 0.0,
			fSlow11: 0.0,
			fRec20: [0.0;2],
			fHslider6: 0.0,
			fSlow12: 0.0,
			fRec21: [0.0;2],
			fVec1: [0.0;2],
			fRec19: [0.0;2],
			fHslider7: 0.0,
			fSlow13: 0.0,
			fRec22: [0.0;2],
			IOTA0: 0,
			fVec2: [0.0;131072],
			fConst3: 0.0,
			fHslider8: 0.0,
			fSlow14: 0.0,
			fSlow15: 0.0,
			fSlow16: 0.0,
			fHslider9: 0.0,
			fSlow17: 0.0,
			fSlow18: 0.0,
			fSlow19: 0.0,
			fConst4: 0.0,
			fHslider10: 0.0,
			fSlow20: 0.0,
			fSlow21: 0.0,
			fSlow22: 0.0,
			fSlow23: 0.0,
			fSlow24: 0.0,
			fSlow25: 0.0,
			fSlow26: 0.0,
			fVec3: [0.0;65536],
			iSlow27: 0,
			iSlow28: 0,
			fSlow29: 0.0,
			fSlow30: 0.0,
			iSlow31: 0,
			fSlow32: 0.0,
			fSlow33: 0.0,
			iSlow34: 0,
			fSlow35: 0.0,
			iSlow36: 0,
			fVec4: [0.0;2],
			fRec24: [0.0;2],
			fRec23: [0.0;2],
			fVec5: [0.0;1024],
			fRec16: [0.0;2],
			fRec27: [0.0;2],
			fSlow37: 0.0,
			fRec29: [0.0;2],
			fRec30: [0.0;2],
			fVec6: [0.0;2],
			fRec28: [0.0;2],
			fRec31: [0.0;2],
			fVec7: [0.0;131072],
			fVec8: [0.0;65536],
			fVec9: [0.0;2],
			fRec33: [0.0;2],
			fRec32: [0.0;2],
			fVec10: [0.0;1024],
			fRec25: [0.0;2],
			fSlow38: 0.0,
			fRec37: [0.0;2],
			fRec38: [0.0;2],
			fVec11: [0.0;2],
			fRec36: [0.0;2],
			fRec39: [0.0;2],
			fVec12: [0.0;131072],
			fVec13: [0.0;1024],
			fRec34: [0.0;2],
			fRec42: [0.0;2],
			fSlow39: 0.0,
			fRec44: [0.0;2],
			fRec45: [0.0;2],
			fVec14: [0.0;2],
			fRec43: [0.0;2],
			fRec46: [0.0;2],
			fVec15: [0.0;131072],
			fVec16: [0.0;1024],
			fRec40: [0.0;2],
			fSlow40: 0.0,
			fRec50: [0.0;2],
			fRec51: [0.0;2],
			fVec17: [0.0;2],
			fRec49: [0.0;2],
			fRec52: [0.0;2],
			fVec18: [0.0;131072],
			fVec19: [0.0;1024],
			fRec47: [0.0;2],
			fRec55: [0.0;2],
			fSlow41: 0.0,
			fRec57: [0.0;2],
			fRec58: [0.0;2],
			fVec20: [0.0;2],
			fRec56: [0.0;2],
			fRec59: [0.0;2],
			fVec21: [0.0;131072],
			fVec22: [0.0;1024],
			fRec53: [0.0;2],
			fSlow42: 0.0,
			fRec63: [0.0;2],
			fRec64: [0.0;2],
			fVec23: [0.0;2],
			fRec62: [0.0;2],
			fRec65: [0.0;2],
			fVec24: [0.0;65536],
			fVec25: [0.0;1024],
			fRec60: [0.0;2],
			fRec68: [0.0;2],
			fSlow43: 0.0,
			fRec70: [0.0;2],
			fRec71: [0.0;2],
			fVec26: [0.0;2],
			fRec69: [0.0;2],
			fRec72: [0.0;2],
			fVec27: [0.0;131072],
			fVec28: [0.0;1024],
			fRec66: [0.0;2],
			fSlow44: 0.0,
			fRec76: [0.0;2],
			fRec77: [0.0;2],
			fVec29: [0.0;2],
			fRec75: [0.0;2],
			fRec78: [0.0;2],
			fVec30: [0.0;131072],
			fVec31: [0.0;1024],
			fRec73: [0.0;2],
			fRec81: [0.0;2],
			fSlow45: 0.0,
			fRec83: [0.0;2],
			fRec84: [0.0;2],
			fVec32: [0.0;2],
			fRec82: [0.0;2],
			fRec85: [0.0;2],
			fVec33: [0.0;131072],
			fVec34: [0.0;1024],
			fRec79: [0.0;2],
			fSlow46: 0.0,
			fRec89: [0.0;2],
			fRec90: [0.0;2],
			fVec35: [0.0;2],
			fRec88: [0.0;2],
			fRec91: [0.0;2],
			fVec36: [0.0;65536],
			fVec37: [0.0;1024],
			fRec86: [0.0;2],
			fRec94: [0.0;2],
			fSlow47: 0.0,
			fRec96: [0.0;2],
			fRec97: [0.0;2],
			fVec38: [0.0;2],
			fRec95: [0.0;2],
			fRec98: [0.0;2],
			fVec39: [0.0;131072],
			fVec40: [0.0;1024],
			fRec92: [0.0;2],
			fSlow48: 0.0,
			fRec102: [0.0;2],
			fRec103: [0.0;2],
			fVec41: [0.0;2],
			fRec101: [0.0;2],
			fRec104: [0.0;2],
			fVec42: [0.0;131072],
			fVec43: [0.0;1024],
			fRec99: [0.0;2],
			fRec107: [0.0;2],
			fSlow49: 0.0,
			fRec109: [0.0;2],
			fRec110: [0.0;2],
			fVec44: [0.0;2],
			fRec108: [0.0;2],
			fRec111: [0.0;2],
			fVec45: [0.0;65536],
			fVec46: [0.0;1024],
			fRec105: [0.0;2],
			fSlow50: 0.0,
			fRec115: [0.0;2],
			fRec116: [0.0;2],
			fVec47: [0.0;2],
			fRec114: [0.0;2],
			fRec117: [0.0;2],
			fVec48: [0.0;65536],
			fVec49: [0.0;1024],
			fRec112: [0.0;2],
			fSlow51: 0.0,
			fRec121: [0.0;2],
			fRec122: [0.0;2],
			fVec50: [0.0;2],
			fRec120: [0.0;2],
			fRec123: [0.0;2],
			fVec51: [0.0;131072],
			fVec52: [0.0;1024],
			fRec118: [0.0;2],
			fRec0: [0.0;3],
			fRec1: [0.0;3],
			fRec2: [0.0;3],
			fRec3: [0.0;3],
			fRec4: [0.0;3],
			fRec5: [0.0;3],
			fRec6: [0.0;3],
			fRec7: [0.0;3],
			fRec8: [0.0;3],
			fRec9: [0.0;3],
			fRec10: [0.0;3],
			fRec11: [0.0;3],
			fRec12: [0.0;3],
			fRec13: [0.0;3],
			fRec14: [0.0;3],
			fRec15: [0.0;3],
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("aanl.lib/name", r"Faust Antialiased Nonlinearities");
		m.declare("aanl.lib/version", r"1.4.1");
		m.declare("analyzers.lib/name", r"Faust Analyzer Library");
		m.declare("analyzers.lib/version", r"1.2.0");
		m.declare("basics.lib/name", r"Faust Basic Element Library");
		m.declare("basics.lib/version", r"1.21.0");
		m.declare("compile_options", r"-lang rust -ec -ct 1 -cn VitalRevDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
		m.declare("delays.lib/fdelayltv:author", r"Julius O. Smith III");
		m.declare("delays.lib/name", r"Faust Delay Library");
		m.declare("delays.lib/version", r"1.2.0");
		m.declare("filename", r"vital_rev.dsp");
		m.declare("filters.lib/allpass_comb:author", r"Julius O. Smith III");
		m.declare("filters.lib/allpass_comb:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/allpass_comb:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/filterbank:author", r"Julius O. Smith III");
		m.declare("filters.lib/filterbank:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/filterbank:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/highpass:author", r"Julius O. Smith III");
		m.declare("filters.lib/highpass:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/highshelf:author", r"Julius O. Smith III");
		m.declare("filters.lib/highshelf:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/highshelf:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/lowpass0_highpass1", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/lowpass0_highpass1:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowpass:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowpass:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowpass:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/lowshelf:author", r"Julius O. Smith III");
		m.declare("filters.lib/lowshelf:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/lowshelf:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/name", r"Faust Filters Library");
		m.declare("filters.lib/tf1:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf1:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf1:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/tf1s:author", r"Julius O. Smith III");
		m.declare("filters.lib/tf1s:copyright", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/tf1s:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/version", r"1.7.1");
		m.declare("interpolators.lib/interpolate_linear:author", r"Stéphane Letz");
		m.declare("interpolators.lib/interpolate_linear:licence", r"MIT");
		m.declare("interpolators.lib/name", r"Faust Interpolator Library");
		m.declare("interpolators.lib/remap:author", r"David Braun");
		m.declare("interpolators.lib/version", r"1.4.0");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("misceffects.lib/dryWetMixerConstantPower:author", r"David Braun, revised by Stéphane Letz");
		m.declare("misceffects.lib/name", r"Misc Effects Library");
		m.declare("misceffects.lib/version", r"2.5.1");
		m.declare("name", r"vital_rev");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
		m.declare("reverbs.lib/name", r"Faust Reverb Library");
		m.declare("reverbs.lib/version", r"1.4.0");
		m.declare("reverbs.lib/vital_rev:author", r"David Braun");
		m.declare("reverbs.lib/vital_rev:license", r"GPL-3.0");
		m.declare("routes.lib/name", r"Faust Signal Routing Library");
		m.declare("routes.lib/version", r"1.2.0");
		m.declare("signals.lib/name", r"Faust Signal Routing Library");
		m.declare("signals.lib/version", r"1.6.0");
		m.declare("spats.lib/name", r"Faust Spatialization Library");
		m.declare("spats.lib/version", r"1.2.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 0.75;
		self.fHslider1 = 0.3;
		self.fHslider2 = 0.65;
		self.fHslider3 = 0.55;
		self.fHslider4 = 0.7;
		self.fHslider5 = 0.5;
		self.fHslider6 = 0.4;
		self.fHslider7 = 0.5;
		self.fHslider8 = 0.9;
		self.fHslider9 = 0.2;
		self.fHslider10 = 0.0;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.iVec0[l0 as usize] = 0;
		}
		for l1 in 0..2 {
			self.fRec18[l1 as usize] = 0.0;
		}
		for l2 in 0..2 {
			self.fRec20[l2 as usize] = 0.0;
		}
		for l3 in 0..2 {
			self.fRec21[l3 as usize] = 0.0;
		}
		for l4 in 0..2 {
			self.fVec1[l4 as usize] = 0.0;
		}
		for l5 in 0..2 {
			self.fRec19[l5 as usize] = 0.0;
		}
		for l6 in 0..2 {
			self.fRec22[l6 as usize] = 0.0;
		}
		self.IOTA0 = 0;
		for l7 in 0..131072 {
			self.fVec2[l7 as usize] = 0.0;
		}
		for l8 in 0..65536 {
			self.fVec3[l8 as usize] = 0.0;
		}
		for l9 in 0..2 {
			self.fVec4[l9 as usize] = 0.0;
		}
		for l10 in 0..2 {
			self.fRec24[l10 as usize] = 0.0;
		}
		for l11 in 0..2 {
			self.fRec23[l11 as usize] = 0.0;
		}
		for l12 in 0..1024 {
			self.fVec5[l12 as usize] = 0.0;
		}
		for l13 in 0..2 {
			self.fRec16[l13 as usize] = 0.0;
		}
		for l14 in 0..2 {
			self.fRec27[l14 as usize] = 0.0;
		}
		for l15 in 0..2 {
			self.fRec29[l15 as usize] = 0.0;
		}
		for l16 in 0..2 {
			self.fRec30[l16 as usize] = 0.0;
		}
		for l17 in 0..2 {
			self.fVec6[l17 as usize] = 0.0;
		}
		for l18 in 0..2 {
			self.fRec28[l18 as usize] = 0.0;
		}
		for l19 in 0..2 {
			self.fRec31[l19 as usize] = 0.0;
		}
		for l20 in 0..131072 {
			self.fVec7[l20 as usize] = 0.0;
		}
		for l21 in 0..65536 {
			self.fVec8[l21 as usize] = 0.0;
		}
		for l22 in 0..2 {
			self.fVec9[l22 as usize] = 0.0;
		}
		for l23 in 0..2 {
			self.fRec33[l23 as usize] = 0.0;
		}
		for l24 in 0..2 {
			self.fRec32[l24 as usize] = 0.0;
		}
		for l25 in 0..1024 {
			self.fVec10[l25 as usize] = 0.0;
		}
		for l26 in 0..2 {
			self.fRec25[l26 as usize] = 0.0;
		}
		for l27 in 0..2 {
			self.fRec37[l27 as usize] = 0.0;
		}
		for l28 in 0..2 {
			self.fRec38[l28 as usize] = 0.0;
		}
		for l29 in 0..2 {
			self.fVec11[l29 as usize] = 0.0;
		}
		for l30 in 0..2 {
			self.fRec36[l30 as usize] = 0.0;
		}
		for l31 in 0..2 {
			self.fRec39[l31 as usize] = 0.0;
		}
		for l32 in 0..131072 {
			self.fVec12[l32 as usize] = 0.0;
		}
		for l33 in 0..1024 {
			self.fVec13[l33 as usize] = 0.0;
		}
		for l34 in 0..2 {
			self.fRec34[l34 as usize] = 0.0;
		}
		for l35 in 0..2 {
			self.fRec42[l35 as usize] = 0.0;
		}
		for l36 in 0..2 {
			self.fRec44[l36 as usize] = 0.0;
		}
		for l37 in 0..2 {
			self.fRec45[l37 as usize] = 0.0;
		}
		for l38 in 0..2 {
			self.fVec14[l38 as usize] = 0.0;
		}
		for l39 in 0..2 {
			self.fRec43[l39 as usize] = 0.0;
		}
		for l40 in 0..2 {
			self.fRec46[l40 as usize] = 0.0;
		}
		for l41 in 0..131072 {
			self.fVec15[l41 as usize] = 0.0;
		}
		for l42 in 0..1024 {
			self.fVec16[l42 as usize] = 0.0;
		}
		for l43 in 0..2 {
			self.fRec40[l43 as usize] = 0.0;
		}
		for l44 in 0..2 {
			self.fRec50[l44 as usize] = 0.0;
		}
		for l45 in 0..2 {
			self.fRec51[l45 as usize] = 0.0;
		}
		for l46 in 0..2 {
			self.fVec17[l46 as usize] = 0.0;
		}
		for l47 in 0..2 {
			self.fRec49[l47 as usize] = 0.0;
		}
		for l48 in 0..2 {
			self.fRec52[l48 as usize] = 0.0;
		}
		for l49 in 0..131072 {
			self.fVec18[l49 as usize] = 0.0;
		}
		for l50 in 0..1024 {
			self.fVec19[l50 as usize] = 0.0;
		}
		for l51 in 0..2 {
			self.fRec47[l51 as usize] = 0.0;
		}
		for l52 in 0..2 {
			self.fRec55[l52 as usize] = 0.0;
		}
		for l53 in 0..2 {
			self.fRec57[l53 as usize] = 0.0;
		}
		for l54 in 0..2 {
			self.fRec58[l54 as usize] = 0.0;
		}
		for l55 in 0..2 {
			self.fVec20[l55 as usize] = 0.0;
		}
		for l56 in 0..2 {
			self.fRec56[l56 as usize] = 0.0;
		}
		for l57 in 0..2 {
			self.fRec59[l57 as usize] = 0.0;
		}
		for l58 in 0..131072 {
			self.fVec21[l58 as usize] = 0.0;
		}
		for l59 in 0..1024 {
			self.fVec22[l59 as usize] = 0.0;
		}
		for l60 in 0..2 {
			self.fRec53[l60 as usize] = 0.0;
		}
		for l61 in 0..2 {
			self.fRec63[l61 as usize] = 0.0;
		}
		for l62 in 0..2 {
			self.fRec64[l62 as usize] = 0.0;
		}
		for l63 in 0..2 {
			self.fVec23[l63 as usize] = 0.0;
		}
		for l64 in 0..2 {
			self.fRec62[l64 as usize] = 0.0;
		}
		for l65 in 0..2 {
			self.fRec65[l65 as usize] = 0.0;
		}
		for l66 in 0..65536 {
			self.fVec24[l66 as usize] = 0.0;
		}
		for l67 in 0..1024 {
			self.fVec25[l67 as usize] = 0.0;
		}
		for l68 in 0..2 {
			self.fRec60[l68 as usize] = 0.0;
		}
		for l69 in 0..2 {
			self.fRec68[l69 as usize] = 0.0;
		}
		for l70 in 0..2 {
			self.fRec70[l70 as usize] = 0.0;
		}
		for l71 in 0..2 {
			self.fRec71[l71 as usize] = 0.0;
		}
		for l72 in 0..2 {
			self.fVec26[l72 as usize] = 0.0;
		}
		for l73 in 0..2 {
			self.fRec69[l73 as usize] = 0.0;
		}
		for l74 in 0..2 {
			self.fRec72[l74 as usize] = 0.0;
		}
		for l75 in 0..131072 {
			self.fVec27[l75 as usize] = 0.0;
		}
		for l76 in 0..1024 {
			self.fVec28[l76 as usize] = 0.0;
		}
		for l77 in 0..2 {
			self.fRec66[l77 as usize] = 0.0;
		}
		for l78 in 0..2 {
			self.fRec76[l78 as usize] = 0.0;
		}
		for l79 in 0..2 {
			self.fRec77[l79 as usize] = 0.0;
		}
		for l80 in 0..2 {
			self.fVec29[l80 as usize] = 0.0;
		}
		for l81 in 0..2 {
			self.fRec75[l81 as usize] = 0.0;
		}
		for l82 in 0..2 {
			self.fRec78[l82 as usize] = 0.0;
		}
		for l83 in 0..131072 {
			self.fVec30[l83 as usize] = 0.0;
		}
		for l84 in 0..1024 {
			self.fVec31[l84 as usize] = 0.0;
		}
		for l85 in 0..2 {
			self.fRec73[l85 as usize] = 0.0;
		}
		for l86 in 0..2 {
			self.fRec81[l86 as usize] = 0.0;
		}
		for l87 in 0..2 {
			self.fRec83[l87 as usize] = 0.0;
		}
		for l88 in 0..2 {
			self.fRec84[l88 as usize] = 0.0;
		}
		for l89 in 0..2 {
			self.fVec32[l89 as usize] = 0.0;
		}
		for l90 in 0..2 {
			self.fRec82[l90 as usize] = 0.0;
		}
		for l91 in 0..2 {
			self.fRec85[l91 as usize] = 0.0;
		}
		for l92 in 0..131072 {
			self.fVec33[l92 as usize] = 0.0;
		}
		for l93 in 0..1024 {
			self.fVec34[l93 as usize] = 0.0;
		}
		for l94 in 0..2 {
			self.fRec79[l94 as usize] = 0.0;
		}
		for l95 in 0..2 {
			self.fRec89[l95 as usize] = 0.0;
		}
		for l96 in 0..2 {
			self.fRec90[l96 as usize] = 0.0;
		}
		for l97 in 0..2 {
			self.fVec35[l97 as usize] = 0.0;
		}
		for l98 in 0..2 {
			self.fRec88[l98 as usize] = 0.0;
		}
		for l99 in 0..2 {
			self.fRec91[l99 as usize] = 0.0;
		}
		for l100 in 0..65536 {
			self.fVec36[l100 as usize] = 0.0;
		}
		for l101 in 0..1024 {
			self.fVec37[l101 as usize] = 0.0;
		}
		for l102 in 0..2 {
			self.fRec86[l102 as usize] = 0.0;
		}
		for l103 in 0..2 {
			self.fRec94[l103 as usize] = 0.0;
		}
		for l104 in 0..2 {
			self.fRec96[l104 as usize] = 0.0;
		}
		for l105 in 0..2 {
			self.fRec97[l105 as usize] = 0.0;
		}
		for l106 in 0..2 {
			self.fVec38[l106 as usize] = 0.0;
		}
		for l107 in 0..2 {
			self.fRec95[l107 as usize] = 0.0;
		}
		for l108 in 0..2 {
			self.fRec98[l108 as usize] = 0.0;
		}
		for l109 in 0..131072 {
			self.fVec39[l109 as usize] = 0.0;
		}
		for l110 in 0..1024 {
			self.fVec40[l110 as usize] = 0.0;
		}
		for l111 in 0..2 {
			self.fRec92[l111 as usize] = 0.0;
		}
		for l112 in 0..2 {
			self.fRec102[l112 as usize] = 0.0;
		}
		for l113 in 0..2 {
			self.fRec103[l113 as usize] = 0.0;
		}
		for l114 in 0..2 {
			self.fVec41[l114 as usize] = 0.0;
		}
		for l115 in 0..2 {
			self.fRec101[l115 as usize] = 0.0;
		}
		for l116 in 0..2 {
			self.fRec104[l116 as usize] = 0.0;
		}
		for l117 in 0..131072 {
			self.fVec42[l117 as usize] = 0.0;
		}
		for l118 in 0..1024 {
			self.fVec43[l118 as usize] = 0.0;
		}
		for l119 in 0..2 {
			self.fRec99[l119 as usize] = 0.0;
		}
		for l120 in 0..2 {
			self.fRec107[l120 as usize] = 0.0;
		}
		for l121 in 0..2 {
			self.fRec109[l121 as usize] = 0.0;
		}
		for l122 in 0..2 {
			self.fRec110[l122 as usize] = 0.0;
		}
		for l123 in 0..2 {
			self.fVec44[l123 as usize] = 0.0;
		}
		for l124 in 0..2 {
			self.fRec108[l124 as usize] = 0.0;
		}
		for l125 in 0..2 {
			self.fRec111[l125 as usize] = 0.0;
		}
		for l126 in 0..65536 {
			self.fVec45[l126 as usize] = 0.0;
		}
		for l127 in 0..1024 {
			self.fVec46[l127 as usize] = 0.0;
		}
		for l128 in 0..2 {
			self.fRec105[l128 as usize] = 0.0;
		}
		for l129 in 0..2 {
			self.fRec115[l129 as usize] = 0.0;
		}
		for l130 in 0..2 {
			self.fRec116[l130 as usize] = 0.0;
		}
		for l131 in 0..2 {
			self.fVec47[l131 as usize] = 0.0;
		}
		for l132 in 0..2 {
			self.fRec114[l132 as usize] = 0.0;
		}
		for l133 in 0..2 {
			self.fRec117[l133 as usize] = 0.0;
		}
		for l134 in 0..65536 {
			self.fVec48[l134 as usize] = 0.0;
		}
		for l135 in 0..1024 {
			self.fVec49[l135 as usize] = 0.0;
		}
		for l136 in 0..2 {
			self.fRec112[l136 as usize] = 0.0;
		}
		for l137 in 0..2 {
			self.fRec121[l137 as usize] = 0.0;
		}
		for l138 in 0..2 {
			self.fRec122[l138 as usize] = 0.0;
		}
		for l139 in 0..2 {
			self.fVec50[l139 as usize] = 0.0;
		}
		for l140 in 0..2 {
			self.fRec120[l140 as usize] = 0.0;
		}
		for l141 in 0..2 {
			self.fRec123[l141 as usize] = 0.0;
		}
		for l142 in 0..131072 {
			self.fVec51[l142 as usize] = 0.0;
		}
		for l143 in 0..1024 {
			self.fVec52[l143 as usize] = 0.0;
		}
		for l144 in 0..2 {
			self.fRec118[l144 as usize] = 0.0;
		}
		for l145 in 0..3 {
			self.fRec0[l145 as usize] = 0.0;
		}
		for l146 in 0..3 {
			self.fRec1[l146 as usize] = 0.0;
		}
		for l147 in 0..3 {
			self.fRec2[l147 as usize] = 0.0;
		}
		for l148 in 0..3 {
			self.fRec3[l148 as usize] = 0.0;
		}
		for l149 in 0..3 {
			self.fRec4[l149 as usize] = 0.0;
		}
		for l150 in 0..3 {
			self.fRec5[l150 as usize] = 0.0;
		}
		for l151 in 0..3 {
			self.fRec6[l151 as usize] = 0.0;
		}
		for l152 in 0..3 {
			self.fRec7[l152 as usize] = 0.0;
		}
		for l153 in 0..3 {
			self.fRec8[l153 as usize] = 0.0;
		}
		for l154 in 0..3 {
			self.fRec9[l154 as usize] = 0.0;
		}
		for l155 in 0..3 {
			self.fRec10[l155 as usize] = 0.0;
		}
		for l156 in 0..3 {
			self.fRec11[l156 as usize] = 0.0;
		}
		for l157 in 0..3 {
			self.fRec12[l157 as usize] = 0.0;
		}
		for l158 in 0..3 {
			self.fRec13[l158 as usize] = 0.0;
		}
		for l159 in 0..3 {
			self.fRec14[l159 as usize] = 0.0;
		}
		for l160 in 0..3 {
			self.fRec15[l160 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = 1.0 / self.fConst0;
		self.fConst2 = 1382.3008 / self.fConst0;
		self.fConst3 = 0.62716556 * self.fConst0;
		self.fConst4 = 0.3 * self.fConst0;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		VitalRevDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("vital_rev");
		ui_interface.add_horizontal_slider("a_prelow", ParamIndex(0), 0.2, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("b_prehigh", ParamIndex(1), 0.9, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("c_lowcut", ParamIndex(2), 0.5, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("d_highcut", ParamIndex(3), 0.7, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("e_lowgain", ParamIndex(4), 0.4, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("f_highgain", ParamIndex(5), 0.5, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("g_chorus", ParamIndex(6), 0.3, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("h_chorusfreq", ParamIndex(7), 0.65, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("i_predelay", ParamIndex(8), 0.0, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("j_time", ParamIndex(9), 0.55, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("k_size", ParamIndex(10), 0.75, 0.0, 1.0, 0.001);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			10 => Some(self.fHslider0),
			6 => Some(self.fHslider1),
			8 => Some(self.fHslider10),
			7 => Some(self.fHslider2),
			9 => Some(self.fHslider3),
			3 => Some(self.fHslider4),
			2 => Some(self.fHslider5),
			4 => Some(self.fHslider6),
			5 => Some(self.fHslider7),
			1 => Some(self.fHslider8),
			0 => Some(self.fHslider9),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			10 => { self.fHslider0 = value }
			6 => { self.fHslider1 = value }
			8 => { self.fHslider10 = value }
			7 => { self.fHslider2 = value }
			9 => { self.fHslider3 = value }
			3 => { self.fHslider4 = value }
			2 => { self.fHslider5 = value }
			4 => { self.fHslider6 = value }
			5 => { self.fHslider7 = value }
			1 => { self.fHslider8 = value }
			0 => { self.fHslider9 = value }
			_ => {}
		}
	}
	
	pub fn control(&mut self) {
		// Obtaining locks on 0 static var(s)
	self.fSlow0 = F32::powf(2.0, 4.0 * F32::max(0.0, F32::min(1.0, self.fHslider0)) + -3.0);
		self.fSlow1 = self.fConst0 * self.fSlow0;
		self.fSlow2 = 0.05668934 * VitalRevDsp_faustpower2_f(F32::max(0.0, F32::min(1.0, self.fHslider1)));
		self.fSlow3 = self.fConst1 * F32::min(16.0, F32::exp(11.0 * self.fHslider2 + -8.0));
		self.fSlow4 = self.fSlow0 / F32::max(0.1, F32::min(1e+02, F32::exp(12.0 * self.fHslider3 + -6.0)));
		self.fSlow5 = F32::powf(0.001, 0.15313378 * self.fSlow4);
		self.fSlow6 = 1.0 / F32::tan(self.fConst2 * F32::powf(2.0, 0.083333336 * (119.0 * F32::max(0.0, F32::min(1.0, self.fHslider4)) + -53.0)));
		self.fSlow7 = 1.0 / (self.fSlow6 + 1.0);
		self.fSlow8 = 1.0 - self.fSlow6;
		self.fSlow9 = 1.0 / F32::tan(self.fConst2 * F32::powf(2.0, 0.083333336 * (119.0 * F32::max(0.0, F32::min(1.0, self.fHslider5)) + -53.0)));
		self.fSlow10 = 1.0 / (self.fSlow9 + 1.0);
		self.fSlow11 = 1.0 - self.fSlow9;
		self.fSlow12 = F32::powf(1e+01, -(1.2 * (1.0 - F32::max(0.0, F32::min(1.0, self.fHslider6)))));
		self.fSlow13 = F32::powf(1e+01, -(1.2 * (1.0 - F32::max(0.0, F32::min(1.0, self.fHslider7)))));
		self.fSlow14 = 1.0 / F32::tan(self.fConst2 * F32::powf(2.0, 0.083333336 * (119.0 * F32::max(0.0, F32::min(1.0, self.fHslider8)) + -53.0)));
		self.fSlow15 = 1.0 / (self.fSlow14 + 1.0);
		self.fSlow16 = 1.0 - self.fSlow14;
		self.fSlow17 = 1.0 / F32::tan(self.fConst2 * F32::powf(2.0, 0.083333336 * (119.0 * F32::max(0.0, F32::min(1.0, self.fHslider9)) + -53.0)));
		self.fSlow18 = 1.0 / (self.fSlow17 + 1.0);
		self.fSlow19 = 1.0 - self.fSlow17;
		self.fSlow20 = F32::max(1.0, self.fConst4 * F32::max(0.0, F32::min(1.0, self.fHslider10)));
		self.fSlow21 = self.fSlow20 + -0.999995;
		self.fSlow22 = F32::floor(self.fSlow21);
		self.fSlow23 = self.fSlow20 + (-3.0 - self.fSlow22);
		self.fSlow24 = self.fSlow20 + (-2.0 - self.fSlow22);
		self.fSlow25 = self.fSlow20 - self.fSlow22;
		self.fSlow26 = 0.5 * self.fSlow25;
		self.iSlow27 = (self.fSlow21) as i32;
		self.iSlow28 = (F32::min(self.fConst4, (std::cmp::max(0, i32::wrapping_add(self.iSlow27, 1))) as F32)) as i32;
		self.fSlow29 = self.fSlow20 + (-1.0 - self.fSlow22);
		self.fSlow30 = 0.16666667 * self.fSlow29;
		self.iSlow31 = (F32::min(self.fConst4, (std::cmp::max(0, self.iSlow27)) as F32)) as i32;
		self.fSlow32 = self.fSlow25 * self.fSlow29;
		self.fSlow33 = 0.5 * self.fSlow32;
		self.iSlow34 = (F32::min(self.fConst4, (std::cmp::max(0, i32::wrapping_add(self.iSlow27, 2))) as F32)) as i32;
		self.fSlow35 = 0.16666667 * self.fSlow32 * self.fSlow24;
		self.iSlow36 = (F32::min(self.fConst4, (std::cmp::max(0, i32::wrapping_add(self.iSlow27, 3))) as F32)) as i32;
		self.fSlow37 = F32::powf(0.001, 0.12767006 * self.fSlow4);
		self.fSlow38 = F32::powf(0.001, 0.17490976 * self.fSlow4);
		self.fSlow39 = F32::powf(0.001, 0.12786055 * self.fSlow4);
		self.fSlow40 = F32::powf(0.001, 0.25688207 * self.fSlow4);
		self.fSlow41 = F32::powf(0.001, 0.11940046 * self.fSlow4);
		self.fSlow42 = F32::powf(0.001, 0.08223061 * self.fSlow4);
		self.fSlow43 = F32::powf(0.001, 0.19230045 * self.fSlow4);
		self.fSlow44 = F32::powf(0.001, 0.17470522 * self.fSlow4);
		self.fSlow45 = F32::powf(0.001, 0.14782245 * self.fSlow4);
		self.fSlow46 = F32::powf(0.001, 0.07776644 * self.fSlow4);
		self.fSlow47 = F32::powf(0.001, 0.125 * self.fSlow4);
		self.fSlow48 = F32::powf(0.001, 0.21039456 * self.fSlow4);
		self.fSlow49 = F32::powf(0.001, 0.10252925 * self.fSlow4);
		self.fSlow50 = F32::powf(0.001, 0.070764855 * self.fSlow4);
		self.fSlow51 = F32::powf(0.001, 0.21998005 * self.fSlow4);
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, inputs1, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let inputs1 = inputs1.as_ref()[..count].iter();
		let [outputs0, outputs1, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let outputs1 = outputs1.as_mut()[..count].iter_mut();
		let zipped_iterators = inputs0.zip(inputs1).zip(outputs0).zip(outputs1);
		for (((input0, input1), output0), output1) in zipped_iterators {
			self.iVec0[0] = 1;
			let mut iTemp0: i32 = i32::wrapping_sub(1, self.iVec0[1]);
			let mut fTemp1: F32 = (if iTemp0 != 0 {0.25} else {self.fSlow3 + self.fRec18[1]});
			let mut fTemp2: F32 = fTemp1 - F32::floor(fTemp1);
			self.fRec18[0] = (if (F32::abs(fTemp2) > 1.1754944e-38) as i32 != 0 {fTemp2} else {0.0});
			let mut fTemp3: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec18[0]);
			let mut fTemp4: F32 = F32::max(1.0, self.fSlow1 * (fTemp3 + 0.15313378));
			let mut fTemp5: F32 = fTemp4 + -0.999995;
			let mut fTemp6: F32 = F32::floor(fTemp5);
			let mut fTemp7: F32 = fTemp4 - fTemp6;
			let mut fTemp8: F32 = fTemp4 + (-1.0 - fTemp6);
			let mut fTemp9: F32 = fTemp7 * fTemp8;
			let mut fTemp10: F32 = fTemp4 + (-2.0 - fTemp6);
			let mut fTemp11: F32 = self.fSlow10 * (self.fSlow11 * self.fRec20[1] - self.fSlow9 * (self.fRec0[1] - self.fRec0[2]));
			self.fRec20[0] = (if (F32::abs(-fTemp11) > 1.1754944e-38) as i32 != 0 {-fTemp11} else {0.0});
			let mut fTemp12: F32 = self.fSlow10 * (self.fSlow11 * self.fRec21[1] - (self.fRec0[1] + self.fRec0[2]));
			self.fRec21[0] = (if (F32::abs(-fTemp12) > 1.1754944e-38) as i32 != 0 {-fTemp12} else {0.0});
			let mut fTemp13: F32 = self.fRec20[0] + self.fSlow12 * self.fRec21[0];
			self.fVec1[0] = fTemp13;
			let mut fTemp14: F32 = self.fSlow7 * (self.fSlow8 * self.fRec19[1] - (fTemp13 + self.fVec1[1]));
			self.fRec19[0] = (if (F32::abs(-fTemp14) > 1.1754944e-38) as i32 != 0 {-fTemp14} else {0.0});
			let mut fTemp15: F32 = self.fSlow7 * (self.fSlow8 * self.fRec22[1] - self.fSlow6 * (fTemp13 - self.fVec1[1]));
			self.fRec22[0] = (if (F32::abs(-fTemp15) > 1.1754944e-38) as i32 != 0 {-fTemp15} else {0.0});
			let mut fTemp16: F32 = self.fSlow5 * (self.fRec19[0] + self.fSlow13 * self.fRec22[0]);
			self.fVec2[(self.IOTA0 & 131071) as usize] = fTemp16;
			let mut iTemp17: i32 = (fTemp5) as i32;
			let mut fTemp18: F32 = *input0;
			self.fVec3[(self.IOTA0 & 65535) as usize] = fTemp18;
			let mut fTemp19: F32 = self.fSlow23 * (self.fSlow24 * (self.fSlow26 * self.fVec3[((i32::wrapping_sub(self.IOTA0, self.iSlow28)) & 65535) as usize] - self.fSlow30 * self.fVec3[((i32::wrapping_sub(self.IOTA0, self.iSlow31)) & 65535) as usize]) - self.fSlow33 * self.fVec3[((i32::wrapping_sub(self.IOTA0, self.iSlow34)) & 65535) as usize]) + self.fSlow35 * self.fVec3[((i32::wrapping_sub(self.IOTA0, self.iSlow36)) & 65535) as usize];
			self.fVec4[0] = fTemp19;
			let mut fTemp20: F32 = self.fSlow18 * (self.fSlow19 * self.fRec24[1] - self.fSlow17 * (fTemp19 - self.fVec4[1]));
			self.fRec24[0] = (if (F32::abs(-fTemp20) > 1.1754944e-38) as i32 != 0 {-fTemp20} else {0.0});
			let mut fTemp21: F32 = self.fSlow15 * (self.fSlow16 * self.fRec23[1] - (self.fRec24[0] + self.fRec24[1]));
			self.fRec23[0] = (if (F32::abs(-fTemp21) > 1.1754944e-38) as i32 != 0 {-fTemp21} else {0.0});
			let mut fTemp22: F32 = 0.25 * self.fRec23[0];
			let mut fTemp23: F32 = 0.16666667 * fTemp9 * fTemp10 * self.fVec2[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp17, 3))) as F32)) as i32)) & 131071) as usize] + (fTemp4 + (-3.0 - fTemp6)) * (fTemp10 * (0.5 * fTemp7 * self.fVec2[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp17, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec2[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp17)) as F32)) as i32)) & 131071) as usize] * fTemp8) - 0.5 * fTemp9 * self.fVec2[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp17, 2))) as F32)) as i32)) & 131071) as usize]) + fTemp22 - 0.6 * self.fRec16[1];
			self.fVec5[(self.IOTA0 & 1023) as usize] = fTemp23;
			let mut fTemp24: F32 = self.fVec5[((i32::wrapping_sub(self.IOTA0, 1000)) & 1023) as usize];
			self.fRec16[0] = (if (F32::abs(fTemp24) > 1.1754944e-38) as i32 != 0 {fTemp24} else {0.0});
			let mut fTemp25: F32 = 0.6 * fTemp23;
			let mut fRec17: F32 = (if (F32::abs(fTemp25) > 1.1754944e-38) as i32 != 0 {fTemp25} else {0.0});
			let mut fTemp26: F32 = (if iTemp0 != 0 {0.1875} else {self.fSlow3 + self.fRec27[1]});
			let mut fTemp27: F32 = fTemp26 - F32::floor(fTemp26);
			self.fRec27[0] = (if (F32::abs(fTemp27) > 1.1754944e-38) as i32 != 0 {fTemp27} else {0.0});
			let mut fTemp28: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec27[0]);
			let mut fTemp29: F32 = F32::max(1.0, self.fSlow1 * (0.12767006 - fTemp28));
			let mut fTemp30: F32 = fTemp29 + -0.999995;
			let mut fTemp31: F32 = F32::floor(fTemp30);
			let mut fTemp32: F32 = fTemp29 - fTemp31;
			let mut fTemp33: F32 = fTemp29 + (-1.0 - fTemp31);
			let mut fTemp34: F32 = fTemp32 * fTemp33;
			let mut fTemp35: F32 = fTemp29 + (-2.0 - fTemp31);
			let mut fTemp36: F32 = self.fSlow10 * (self.fSlow11 * self.fRec29[1] - self.fSlow9 * (self.fRec15[1] - self.fRec15[2]));
			self.fRec29[0] = (if (F32::abs(-fTemp36) > 1.1754944e-38) as i32 != 0 {-fTemp36} else {0.0});
			let mut fTemp37: F32 = self.fSlow10 * (self.fSlow11 * self.fRec30[1] - (self.fRec15[1] + self.fRec15[2]));
			self.fRec30[0] = (if (F32::abs(-fTemp37) > 1.1754944e-38) as i32 != 0 {-fTemp37} else {0.0});
			let mut fTemp38: F32 = self.fRec29[0] + self.fSlow12 * self.fRec30[0];
			self.fVec6[0] = fTemp38;
			let mut fTemp39: F32 = self.fSlow7 * (self.fSlow8 * self.fRec28[1] - (fTemp38 + self.fVec6[1]));
			self.fRec28[0] = (if (F32::abs(-fTemp39) > 1.1754944e-38) as i32 != 0 {-fTemp39} else {0.0});
			let mut fTemp40: F32 = self.fSlow7 * (self.fSlow8 * self.fRec31[1] - self.fSlow6 * (fTemp38 - self.fVec6[1]));
			self.fRec31[0] = (if (F32::abs(-fTemp40) > 1.1754944e-38) as i32 != 0 {-fTemp40} else {0.0});
			let mut fTemp41: F32 = self.fSlow37 * (self.fRec28[0] + self.fSlow13 * self.fRec31[0]);
			self.fVec7[(self.IOTA0 & 131071) as usize] = fTemp41;
			let mut iTemp42: i32 = (fTemp30) as i32;
			let mut fTemp43: F32 = *input1;
			self.fVec8[(self.IOTA0 & 65535) as usize] = fTemp43;
			let mut fTemp44: F32 = self.fSlow23 * (self.fSlow24 * (self.fSlow26 * self.fVec8[((i32::wrapping_sub(self.IOTA0, self.iSlow28)) & 65535) as usize] - self.fSlow30 * self.fVec8[((i32::wrapping_sub(self.IOTA0, self.iSlow31)) & 65535) as usize]) - self.fSlow33 * self.fVec8[((i32::wrapping_sub(self.IOTA0, self.iSlow34)) & 65535) as usize]) + self.fSlow35 * self.fVec8[((i32::wrapping_sub(self.IOTA0, self.iSlow36)) & 65535) as usize];
			self.fVec9[0] = fTemp44;
			let mut fTemp45: F32 = self.fSlow18 * (self.fSlow19 * self.fRec33[1] - self.fSlow17 * (fTemp44 - self.fVec9[1]));
			self.fRec33[0] = (if (F32::abs(-fTemp45) > 1.1754944e-38) as i32 != 0 {-fTemp45} else {0.0});
			let mut fTemp46: F32 = self.fSlow15 * (self.fSlow16 * self.fRec32[1] - (self.fRec33[0] + self.fRec33[1]));
			self.fRec32[0] = (if (F32::abs(-fTemp46) > 1.1754944e-38) as i32 != 0 {-fTemp46} else {0.0});
			let mut fTemp47: F32 = 0.25 * self.fRec32[0];
			let mut fTemp48: F32 = 0.16666667 * fTemp34 * fTemp35 * self.fVec7[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp42, 3))) as F32)) as i32)) & 131071) as usize] + fTemp47 + (fTemp29 + (-3.0 - fTemp31)) * (fTemp35 * (0.5 * fTemp32 * self.fVec7[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp42, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec7[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp42)) as F32)) as i32)) & 131071) as usize] * fTemp33) - 0.5 * fTemp34 * self.fVec7[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp42, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec25[1];
			self.fVec10[(self.IOTA0 & 1023) as usize] = fTemp48;
			let mut fTemp49: F32 = self.fVec10[((i32::wrapping_sub(self.IOTA0, 996)) & 1023) as usize];
			self.fRec25[0] = (if (F32::abs(fTemp49) > 1.1754944e-38) as i32 != 0 {fTemp49} else {0.0});
			let mut fTemp50: F32 = 0.6 * fTemp48;
			let mut fRec26: F32 = (if (F32::abs(fTemp50) > 1.1754944e-38) as i32 != 0 {fTemp50} else {0.0});
			let mut fTemp51: F32 = F32::max(1.0, self.fSlow1 * (fTemp28 + 0.17490976));
			let mut fTemp52: F32 = fTemp51 + -0.999995;
			let mut fTemp53: F32 = F32::floor(fTemp52);
			let mut fTemp54: F32 = fTemp51 - fTemp53;
			let mut fTemp55: F32 = fTemp51 + (-1.0 - fTemp53);
			let mut fTemp56: F32 = fTemp54 * fTemp55;
			let mut fTemp57: F32 = fTemp51 + (-2.0 - fTemp53);
			let mut fTemp58: F32 = self.fSlow10 * (self.fSlow11 * self.fRec37[1] - self.fSlow9 * (self.fRec11[1] - self.fRec11[2]));
			self.fRec37[0] = (if (F32::abs(-fTemp58) > 1.1754944e-38) as i32 != 0 {-fTemp58} else {0.0});
			let mut fTemp59: F32 = self.fSlow10 * (self.fSlow11 * self.fRec38[1] - (self.fRec11[1] + self.fRec11[2]));
			self.fRec38[0] = (if (F32::abs(-fTemp59) > 1.1754944e-38) as i32 != 0 {-fTemp59} else {0.0});
			let mut fTemp60: F32 = self.fRec37[0] + self.fSlow12 * self.fRec38[0];
			self.fVec11[0] = fTemp60;
			let mut fTemp61: F32 = self.fSlow7 * (self.fSlow8 * self.fRec36[1] - (fTemp60 + self.fVec11[1]));
			self.fRec36[0] = (if (F32::abs(-fTemp61) > 1.1754944e-38) as i32 != 0 {-fTemp61} else {0.0});
			let mut fTemp62: F32 = self.fSlow7 * (self.fSlow8 * self.fRec39[1] - self.fSlow6 * (fTemp60 - self.fVec11[1]));
			self.fRec39[0] = (if (F32::abs(-fTemp62) > 1.1754944e-38) as i32 != 0 {-fTemp62} else {0.0});
			let mut fTemp63: F32 = self.fSlow38 * (self.fRec36[0] + self.fSlow13 * self.fRec39[0]);
			self.fVec12[(self.IOTA0 & 131071) as usize] = fTemp63;
			let mut iTemp64: i32 = (fTemp52) as i32;
			let mut fTemp65: F32 = 0.16666667 * fTemp56 * fTemp57 * self.fVec12[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp64, 3))) as F32)) as i32)) & 131071) as usize] + fTemp47 + (fTemp51 + (-3.0 - fTemp53)) * (fTemp57 * (0.5 * fTemp54 * self.fVec12[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp64, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec12[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp64)) as F32)) as i32)) & 131071) as usize] * fTemp55) - 0.5 * fTemp56 * self.fVec12[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp64, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec34[1];
			self.fVec13[(self.IOTA0 & 1023) as usize] = fTemp65;
			let mut fTemp66: F32 = self.fVec13[((i32::wrapping_sub(self.IOTA0, 566)) & 1023) as usize];
			self.fRec34[0] = (if (F32::abs(fTemp66) > 1.1754944e-38) as i32 != 0 {fTemp66} else {0.0});
			let mut fTemp67: F32 = 0.6 * fTemp65;
			let mut fRec35: F32 = (if (F32::abs(fTemp67) > 1.1754944e-38) as i32 != 0 {fTemp67} else {0.0});
			let mut fTemp68: F32 = (if iTemp0 != 0 {0.4375} else {self.fSlow3 + self.fRec42[1]});
			let mut fTemp69: F32 = fTemp68 - F32::floor(fTemp68);
			self.fRec42[0] = (if (F32::abs(fTemp69) > 1.1754944e-38) as i32 != 0 {fTemp69} else {0.0});
			let mut fTemp70: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec42[0]);
			let mut fTemp71: F32 = F32::max(1.0, self.fSlow1 * (0.12786055 - fTemp70));
			let mut fTemp72: F32 = fTemp71 + -0.999995;
			let mut fTemp73: F32 = F32::floor(fTemp72);
			let mut fTemp74: F32 = fTemp71 - fTemp73;
			let mut fTemp75: F32 = fTemp71 + (-1.0 - fTemp73);
			let mut fTemp76: F32 = fTemp74 * fTemp75;
			let mut fTemp77: F32 = fTemp71 + (-2.0 - fTemp73);
			let mut fTemp78: F32 = self.fSlow10 * (self.fSlow11 * self.fRec44[1] - self.fSlow9 * (self.fRec7[1] - self.fRec7[2]));
			self.fRec44[0] = (if (F32::abs(-fTemp78) > 1.1754944e-38) as i32 != 0 {-fTemp78} else {0.0});
			let mut fTemp79: F32 = self.fSlow10 * (self.fSlow11 * self.fRec45[1] - (self.fRec7[1] + self.fRec7[2]));
			self.fRec45[0] = (if (F32::abs(-fTemp79) > 1.1754944e-38) as i32 != 0 {-fTemp79} else {0.0});
			let mut fTemp80: F32 = self.fRec44[0] + self.fSlow12 * self.fRec45[0];
			self.fVec14[0] = fTemp80;
			let mut fTemp81: F32 = self.fSlow7 * (self.fSlow8 * self.fRec43[1] - (fTemp80 + self.fVec14[1]));
			self.fRec43[0] = (if (F32::abs(-fTemp81) > 1.1754944e-38) as i32 != 0 {-fTemp81} else {0.0});
			let mut fTemp82: F32 = self.fSlow7 * (self.fSlow8 * self.fRec46[1] - self.fSlow6 * (fTemp80 - self.fVec14[1]));
			self.fRec46[0] = (if (F32::abs(-fTemp82) > 1.1754944e-38) as i32 != 0 {-fTemp82} else {0.0});
			let mut fTemp83: F32 = self.fSlow39 * (self.fRec43[0] + self.fSlow13 * self.fRec46[0]);
			self.fVec15[(self.IOTA0 & 131071) as usize] = fTemp83;
			let mut iTemp84: i32 = (fTemp72) as i32;
			let mut fTemp85: F32 = 0.16666667 * fTemp76 * fTemp77 * self.fVec15[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp84, 3))) as F32)) as i32)) & 131071) as usize] + fTemp47 + (fTemp71 + (-3.0 - fTemp73)) * (fTemp77 * (0.5 * fTemp74 * self.fVec15[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp84, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec15[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp84)) as F32)) as i32)) & 131071) as usize] * fTemp75) - 0.5 * fTemp76 * self.fVec15[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp84, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec40[1];
			self.fVec16[(self.IOTA0 & 1023) as usize] = fTemp85;
			let mut fTemp86: F32 = self.fVec16[((i32::wrapping_sub(self.IOTA0, 852)) & 1023) as usize];
			self.fRec40[0] = (if (F32::abs(fTemp86) > 1.1754944e-38) as i32 != 0 {fTemp86} else {0.0});
			let mut fTemp87: F32 = 0.6 * fTemp85;
			let mut fRec41: F32 = (if (F32::abs(fTemp87) > 1.1754944e-38) as i32 != 0 {fTemp87} else {0.0});
			let mut fTemp88: F32 = F32::max(1.0, self.fSlow1 * (fTemp70 + 0.25688207));
			let mut fTemp89: F32 = fTemp88 + -0.999995;
			let mut fTemp90: F32 = F32::floor(fTemp89);
			let mut fTemp91: F32 = fTemp88 - fTemp90;
			let mut fTemp92: F32 = fTemp88 + (-1.0 - fTemp90);
			let mut fTemp93: F32 = fTemp91 * fTemp92;
			let mut fTemp94: F32 = fTemp88 + (-2.0 - fTemp90);
			let mut fTemp95: F32 = self.fSlow10 * (self.fSlow11 * self.fRec50[1] - self.fSlow9 * (self.fRec3[1] - self.fRec3[2]));
			self.fRec50[0] = (if (F32::abs(-fTemp95) > 1.1754944e-38) as i32 != 0 {-fTemp95} else {0.0});
			let mut fTemp96: F32 = self.fSlow10 * (self.fSlow11 * self.fRec51[1] - (self.fRec3[1] + self.fRec3[2]));
			self.fRec51[0] = (if (F32::abs(-fTemp96) > 1.1754944e-38) as i32 != 0 {-fTemp96} else {0.0});
			let mut fTemp97: F32 = self.fRec50[0] + self.fSlow12 * self.fRec51[0];
			self.fVec17[0] = fTemp97;
			let mut fTemp98: F32 = self.fSlow7 * (self.fSlow8 * self.fRec49[1] - (fTemp97 + self.fVec17[1]));
			self.fRec49[0] = (if (F32::abs(-fTemp98) > 1.1754944e-38) as i32 != 0 {-fTemp98} else {0.0});
			let mut fTemp99: F32 = self.fSlow7 * (self.fSlow8 * self.fRec52[1] - self.fSlow6 * (fTemp97 - self.fVec17[1]));
			self.fRec52[0] = (if (F32::abs(-fTemp99) > 1.1754944e-38) as i32 != 0 {-fTemp99} else {0.0});
			let mut fTemp100: F32 = self.fSlow40 * (self.fRec49[0] + self.fSlow13 * self.fRec52[0]);
			self.fVec18[(self.IOTA0 & 131071) as usize] = fTemp100;
			let mut iTemp101: i32 = (fTemp89) as i32;
			let mut fTemp102: F32 = 0.16666667 * fTemp93 * fTemp94 * self.fVec18[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp101, 3))) as F32)) as i32)) & 131071) as usize] + fTemp47 + (fTemp88 + (-3.0 - fTemp90)) * (fTemp94 * (0.5 * fTemp91 * self.fVec18[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp101, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec18[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp101)) as F32)) as i32)) & 131071) as usize] * fTemp92) - 0.5 * fTemp93 * self.fVec18[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp101, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec47[1];
			self.fVec19[(self.IOTA0 & 1023) as usize] = fTemp102;
			let mut fTemp103: F32 = self.fVec19[((i32::wrapping_sub(self.IOTA0, 875)) & 1023) as usize];
			self.fRec47[0] = (if (F32::abs(fTemp103) > 1.1754944e-38) as i32 != 0 {fTemp103} else {0.0});
			let mut fTemp104: F32 = 0.6 * fTemp102;
			let mut fRec48: F32 = (if (F32::abs(fTemp104) > 1.1754944e-38) as i32 != 0 {fTemp104} else {0.0});
			let mut fTemp105: F32 = (if iTemp0 != 0 {0.125} else {self.fSlow3 + self.fRec55[1]});
			let mut fTemp106: F32 = fTemp105 - F32::floor(fTemp105);
			self.fRec55[0] = (if (F32::abs(fTemp106) > 1.1754944e-38) as i32 != 0 {fTemp106} else {0.0});
			let mut fTemp107: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec55[0]);
			let mut fTemp108: F32 = F32::max(1.0, self.fSlow1 * (0.11940046 - fTemp107));
			let mut fTemp109: F32 = fTemp108 + -0.999995;
			let mut fTemp110: F32 = F32::floor(fTemp109);
			let mut fTemp111: F32 = fTemp108 - fTemp110;
			let mut fTemp112: F32 = fTemp108 + (-1.0 - fTemp110);
			let mut fTemp113: F32 = fTemp111 * fTemp112;
			let mut fTemp114: F32 = fTemp108 + (-2.0 - fTemp110);
			let mut fTemp115: F32 = self.fSlow10 * (self.fSlow11 * self.fRec57[1] - self.fSlow9 * (self.fRec14[1] - self.fRec14[2]));
			self.fRec57[0] = (if (F32::abs(-fTemp115) > 1.1754944e-38) as i32 != 0 {-fTemp115} else {0.0});
			let mut fTemp116: F32 = self.fSlow10 * (self.fSlow11 * self.fRec58[1] - (self.fRec14[1] + self.fRec14[2]));
			self.fRec58[0] = (if (F32::abs(-fTemp116) > 1.1754944e-38) as i32 != 0 {-fTemp116} else {0.0});
			let mut fTemp117: F32 = self.fRec57[0] + self.fSlow12 * self.fRec58[0];
			self.fVec20[0] = fTemp117;
			let mut fTemp118: F32 = self.fSlow7 * (self.fSlow8 * self.fRec56[1] - (fTemp117 + self.fVec20[1]));
			self.fRec56[0] = (if (F32::abs(-fTemp118) > 1.1754944e-38) as i32 != 0 {-fTemp118} else {0.0});
			let mut fTemp119: F32 = self.fSlow7 * (self.fSlow8 * self.fRec59[1] - self.fSlow6 * (fTemp117 - self.fVec20[1]));
			self.fRec59[0] = (if (F32::abs(-fTemp119) > 1.1754944e-38) as i32 != 0 {-fTemp119} else {0.0});
			let mut fTemp120: F32 = self.fSlow41 * (self.fRec56[0] + self.fSlow13 * self.fRec59[0]);
			self.fVec21[(self.IOTA0 & 131071) as usize] = fTemp120;
			let mut iTemp121: i32 = (fTemp109) as i32;
			let mut fTemp122: F32 = 0.16666667 * fTemp113 * fTemp114 * self.fVec21[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp121, 3))) as F32)) as i32)) & 131071) as usize] + fTemp22 + (fTemp108 + (-3.0 - fTemp110)) * (fTemp114 * (0.5 * fTemp111 * self.fVec21[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp121, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec21[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp121)) as F32)) as i32)) & 131071) as usize] * fTemp112) - 0.5 * fTemp113 * self.fVec21[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp121, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec53[1];
			self.fVec22[(self.IOTA0 & 1023) as usize] = fTemp122;
			let mut fTemp123: F32 = self.fVec22[((i32::wrapping_sub(self.IOTA0, 662)) & 1023) as usize];
			self.fRec53[0] = (if (F32::abs(fTemp123) > 1.1754944e-38) as i32 != 0 {fTemp123} else {0.0});
			let mut fTemp124: F32 = 0.6 * fTemp122;
			let mut fRec54: F32 = (if (F32::abs(fTemp124) > 1.1754944e-38) as i32 != 0 {fTemp124} else {0.0});
			let mut fTemp125: F32 = F32::max(1.0, self.fSlow1 * (fTemp107 + 0.08223061));
			let mut fTemp126: F32 = fTemp125 + -0.999995;
			let mut fTemp127: F32 = F32::floor(fTemp126);
			let mut fTemp128: F32 = fTemp125 - fTemp127;
			let mut fTemp129: F32 = fTemp125 + (-1.0 - fTemp127);
			let mut fTemp130: F32 = fTemp128 * fTemp129;
			let mut fTemp131: F32 = fTemp125 + (-2.0 - fTemp127);
			let mut fTemp132: F32 = self.fSlow10 * (self.fSlow11 * self.fRec63[1] - self.fSlow9 * (self.fRec10[1] - self.fRec10[2]));
			self.fRec63[0] = (if (F32::abs(-fTemp132) > 1.1754944e-38) as i32 != 0 {-fTemp132} else {0.0});
			let mut fTemp133: F32 = self.fSlow10 * (self.fSlow11 * self.fRec64[1] - (self.fRec10[1] + self.fRec10[2]));
			self.fRec64[0] = (if (F32::abs(-fTemp133) > 1.1754944e-38) as i32 != 0 {-fTemp133} else {0.0});
			let mut fTemp134: F32 = self.fRec63[0] + self.fSlow12 * self.fRec64[0];
			self.fVec23[0] = fTemp134;
			let mut fTemp135: F32 = self.fSlow7 * (self.fSlow8 * self.fRec62[1] - (fTemp134 + self.fVec23[1]));
			self.fRec62[0] = (if (F32::abs(-fTemp135) > 1.1754944e-38) as i32 != 0 {-fTemp135} else {0.0});
			let mut fTemp136: F32 = self.fSlow7 * (self.fSlow8 * self.fRec65[1] - self.fSlow6 * (fTemp134 - self.fVec23[1]));
			self.fRec65[0] = (if (F32::abs(-fTemp136) > 1.1754944e-38) as i32 != 0 {-fTemp136} else {0.0});
			let mut fTemp137: F32 = self.fSlow42 * (self.fRec62[0] + self.fSlow13 * self.fRec65[0]);
			self.fVec24[(self.IOTA0 & 65535) as usize] = fTemp137;
			let mut iTemp138: i32 = (fTemp126) as i32;
			let mut fTemp139: F32 = 0.16666667 * fTemp130 * fTemp131 * self.fVec24[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp138, 3))) as F32)) as i32)) & 65535) as usize] + fTemp22 + (fTemp125 + (-3.0 - fTemp127)) * (fTemp131 * (0.5 * fTemp128 * self.fVec24[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp138, 1))) as F32)) as i32)) & 65535) as usize] - 0.16666667 * self.fVec24[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp138)) as F32)) as i32)) & 65535) as usize] * fTemp129) - 0.5 * fTemp130 * self.fVec24[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp138, 2))) as F32)) as i32)) & 65535) as usize]) - 0.6 * self.fRec60[1];
			self.fVec25[(self.IOTA0 & 1023) as usize] = fTemp139;
			let mut fTemp140: F32 = self.fVec25[((i32::wrapping_sub(self.IOTA0, 710)) & 1023) as usize];
			self.fRec60[0] = (if (F32::abs(fTemp140) > 1.1754944e-38) as i32 != 0 {fTemp140} else {0.0});
			let mut fTemp141: F32 = 0.6 * fTemp139;
			let mut fRec61: F32 = (if (F32::abs(fTemp141) > 1.1754944e-38) as i32 != 0 {fTemp141} else {0.0});
			let mut fTemp142: F32 = (if iTemp0 != 0 {0.375} else {self.fSlow3 + self.fRec68[1]});
			let mut fTemp143: F32 = fTemp142 - F32::floor(fTemp142);
			self.fRec68[0] = (if (F32::abs(fTemp143) > 1.1754944e-38) as i32 != 0 {fTemp143} else {0.0});
			let mut fTemp144: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec68[0]);
			let mut fTemp145: F32 = F32::max(1.0, self.fSlow1 * (0.19230045 - fTemp144));
			let mut fTemp146: F32 = fTemp145 + -0.999995;
			let mut fTemp147: F32 = F32::floor(fTemp146);
			let mut fTemp148: F32 = fTemp145 - fTemp147;
			let mut fTemp149: F32 = fTemp145 + (-1.0 - fTemp147);
			let mut fTemp150: F32 = fTemp148 * fTemp149;
			let mut fTemp151: F32 = fTemp145 + (-2.0 - fTemp147);
			let mut fTemp152: F32 = self.fSlow10 * (self.fSlow11 * self.fRec70[1] - self.fSlow9 * (self.fRec6[1] - self.fRec6[2]));
			self.fRec70[0] = (if (F32::abs(-fTemp152) > 1.1754944e-38) as i32 != 0 {-fTemp152} else {0.0});
			let mut fTemp153: F32 = self.fSlow10 * (self.fSlow11 * self.fRec71[1] - (self.fRec6[1] + self.fRec6[2]));
			self.fRec71[0] = (if (F32::abs(-fTemp153) > 1.1754944e-38) as i32 != 0 {-fTemp153} else {0.0});
			let mut fTemp154: F32 = self.fRec70[0] + self.fSlow12 * self.fRec71[0];
			self.fVec26[0] = fTemp154;
			let mut fTemp155: F32 = self.fSlow7 * (self.fSlow8 * self.fRec69[1] - (fTemp154 + self.fVec26[1]));
			self.fRec69[0] = (if (F32::abs(-fTemp155) > 1.1754944e-38) as i32 != 0 {-fTemp155} else {0.0});
			let mut fTemp156: F32 = self.fSlow7 * (self.fSlow8 * self.fRec72[1] - self.fSlow6 * (fTemp154 - self.fVec26[1]));
			self.fRec72[0] = (if (F32::abs(-fTemp156) > 1.1754944e-38) as i32 != 0 {-fTemp156} else {0.0});
			let mut fTemp157: F32 = self.fSlow43 * (self.fRec69[0] + self.fSlow13 * self.fRec72[0]);
			self.fVec27[(self.IOTA0 & 131071) as usize] = fTemp157;
			let mut iTemp158: i32 = (fTemp146) as i32;
			let mut fTemp159: F32 = 0.16666667 * fTemp150 * fTemp151 * self.fVec27[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp158, 3))) as F32)) as i32)) & 131071) as usize] + fTemp22 + (fTemp145 + (-3.0 - fTemp147)) * (fTemp151 * (0.5 * fTemp148 * self.fVec27[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp158, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec27[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp158)) as F32)) as i32)) & 131071) as usize] * fTemp149) - 0.5 * fTemp150 * self.fVec27[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp158, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec66[1];
			self.fVec28[(self.IOTA0 & 1023) as usize] = fTemp159;
			let mut fTemp160: F32 = self.fVec28[((i32::wrapping_sub(self.IOTA0, 906)) & 1023) as usize];
			self.fRec66[0] = (if (F32::abs(fTemp160) > 1.1754944e-38) as i32 != 0 {fTemp160} else {0.0});
			let mut fTemp161: F32 = 0.6 * fTemp159;
			let mut fRec67: F32 = (if (F32::abs(fTemp161) > 1.1754944e-38) as i32 != 0 {fTemp161} else {0.0});
			let mut fTemp162: F32 = F32::max(1.0, self.fSlow1 * (fTemp144 + 0.17470522));
			let mut fTemp163: F32 = fTemp162 + -0.999995;
			let mut fTemp164: F32 = F32::floor(fTemp163);
			let mut fTemp165: F32 = fTemp162 - fTemp164;
			let mut fTemp166: F32 = fTemp162 + (-1.0 - fTemp164);
			let mut fTemp167: F32 = fTemp165 * fTemp166;
			let mut fTemp168: F32 = fTemp162 + (-2.0 - fTemp164);
			let mut fTemp169: F32 = self.fSlow10 * (self.fSlow11 * self.fRec76[1] - self.fSlow9 * (self.fRec2[1] - self.fRec2[2]));
			self.fRec76[0] = (if (F32::abs(-fTemp169) > 1.1754944e-38) as i32 != 0 {-fTemp169} else {0.0});
			let mut fTemp170: F32 = self.fSlow10 * (self.fSlow11 * self.fRec77[1] - (self.fRec2[1] + self.fRec2[2]));
			self.fRec77[0] = (if (F32::abs(-fTemp170) > 1.1754944e-38) as i32 != 0 {-fTemp170} else {0.0});
			let mut fTemp171: F32 = self.fRec76[0] + self.fSlow12 * self.fRec77[0];
			self.fVec29[0] = fTemp171;
			let mut fTemp172: F32 = self.fSlow7 * (self.fSlow8 * self.fRec75[1] - (fTemp171 + self.fVec29[1]));
			self.fRec75[0] = (if (F32::abs(-fTemp172) > 1.1754944e-38) as i32 != 0 {-fTemp172} else {0.0});
			let mut fTemp173: F32 = self.fSlow7 * (self.fSlow8 * self.fRec78[1] - self.fSlow6 * (fTemp171 - self.fVec29[1]));
			self.fRec78[0] = (if (F32::abs(-fTemp173) > 1.1754944e-38) as i32 != 0 {-fTemp173} else {0.0});
			let mut fTemp174: F32 = self.fSlow44 * (self.fRec75[0] + self.fSlow13 * self.fRec78[0]);
			self.fVec30[(self.IOTA0 & 131071) as usize] = fTemp174;
			let mut iTemp175: i32 = (fTemp163) as i32;
			let mut fTemp176: F32 = 0.16666667 * fTemp167 * fTemp168 * self.fVec30[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp175, 3))) as F32)) as i32)) & 131071) as usize] + fTemp22 + (fTemp162 + (-3.0 - fTemp164)) * (fTemp168 * (0.5 * fTemp165 * self.fVec30[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp175, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec30[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp175)) as F32)) as i32)) & 131071) as usize] * fTemp166) - 0.5 * fTemp167 * self.fVec30[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp175, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec73[1];
			self.fVec31[(self.IOTA0 & 1023) as usize] = fTemp176;
			let mut fTemp177: F32 = self.fVec31[((i32::wrapping_sub(self.IOTA0, 932)) & 1023) as usize];
			self.fRec73[0] = (if (F32::abs(fTemp177) > 1.1754944e-38) as i32 != 0 {fTemp177} else {0.0});
			let mut fTemp178: F32 = 0.6 * fTemp176;
			let mut fRec74: F32 = (if (F32::abs(fTemp178) > 1.1754944e-38) as i32 != 0 {fTemp178} else {0.0});
			let mut fTemp179: F32 = (if iTemp0 != 0 {0.0625} else {self.fSlow3 + self.fRec81[1]});
			let mut fTemp180: F32 = fTemp179 - F32::floor(fTemp179);
			self.fRec81[0] = (if (F32::abs(fTemp180) > 1.1754944e-38) as i32 != 0 {fTemp180} else {0.0});
			let mut fTemp181: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec81[0]);
			let mut fTemp182: F32 = F32::max(1.0, self.fSlow1 * (0.14782245 - fTemp181));
			let mut fTemp183: F32 = fTemp182 + -0.999995;
			let mut fTemp184: F32 = F32::floor(fTemp183);
			let mut fTemp185: F32 = fTemp182 - fTemp184;
			let mut fTemp186: F32 = fTemp182 + (-1.0 - fTemp184);
			let mut fTemp187: F32 = fTemp185 * fTemp186;
			let mut fTemp188: F32 = fTemp182 + (-2.0 - fTemp184);
			let mut fTemp189: F32 = self.fSlow10 * (self.fSlow11 * self.fRec83[1] - self.fSlow9 * (self.fRec13[1] - self.fRec13[2]));
			self.fRec83[0] = (if (F32::abs(-fTemp189) > 1.1754944e-38) as i32 != 0 {-fTemp189} else {0.0});
			let mut fTemp190: F32 = self.fSlow10 * (self.fSlow11 * self.fRec84[1] - (self.fRec13[1] + self.fRec13[2]));
			self.fRec84[0] = (if (F32::abs(-fTemp190) > 1.1754944e-38) as i32 != 0 {-fTemp190} else {0.0});
			let mut fTemp191: F32 = self.fRec83[0] + self.fSlow12 * self.fRec84[0];
			self.fVec32[0] = fTemp191;
			let mut fTemp192: F32 = self.fSlow7 * (self.fSlow8 * self.fRec82[1] - (fTemp191 + self.fVec32[1]));
			self.fRec82[0] = (if (F32::abs(-fTemp192) > 1.1754944e-38) as i32 != 0 {-fTemp192} else {0.0});
			let mut fTemp193: F32 = self.fSlow7 * (self.fSlow8 * self.fRec85[1] - self.fSlow6 * (fTemp191 - self.fVec32[1]));
			self.fRec85[0] = (if (F32::abs(-fTemp193) > 1.1754944e-38) as i32 != 0 {-fTemp193} else {0.0});
			let mut fTemp194: F32 = self.fSlow45 * (self.fRec82[0] + self.fSlow13 * self.fRec85[0]);
			self.fVec33[(self.IOTA0 & 131071) as usize] = fTemp194;
			let mut iTemp195: i32 = (fTemp183) as i32;
			let mut fTemp196: F32 = 0.16666667 * fTemp187 * fTemp188 * self.fVec33[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp195, 3))) as F32)) as i32)) & 131071) as usize] + fTemp47 + (fTemp182 + (-3.0 - fTemp184)) * (fTemp188 * (0.5 * fTemp185 * self.fVec33[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp195, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec33[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp195)) as F32)) as i32)) & 131071) as usize] * fTemp186) - 0.5 * fTemp187 * self.fVec33[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp195, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec79[1];
			self.fVec34[(self.IOTA0 & 1023) as usize] = fTemp196;
			let mut fTemp197: F32 = self.fVec34[((i32::wrapping_sub(self.IOTA0, 778)) & 1023) as usize];
			self.fRec79[0] = (if (F32::abs(fTemp197) > 1.1754944e-38) as i32 != 0 {fTemp197} else {0.0});
			let mut fTemp198: F32 = 0.6 * fTemp196;
			let mut fRec80: F32 = (if (F32::abs(fTemp198) > 1.1754944e-38) as i32 != 0 {fTemp198} else {0.0});
			let mut fTemp199: F32 = F32::max(1.0, self.fSlow1 * (fTemp181 + 0.07776644));
			let mut fTemp200: F32 = fTemp199 + -0.999995;
			let mut fTemp201: F32 = F32::floor(fTemp200);
			let mut fTemp202: F32 = fTemp199 - fTemp201;
			let mut fTemp203: F32 = fTemp199 + (-1.0 - fTemp201);
			let mut fTemp204: F32 = fTemp202 * fTemp203;
			let mut fTemp205: F32 = fTemp199 + (-2.0 - fTemp201);
			let mut fTemp206: F32 = self.fSlow10 * (self.fSlow11 * self.fRec89[1] - self.fSlow9 * (self.fRec9[1] - self.fRec9[2]));
			self.fRec89[0] = (if (F32::abs(-fTemp206) > 1.1754944e-38) as i32 != 0 {-fTemp206} else {0.0});
			let mut fTemp207: F32 = self.fSlow10 * (self.fSlow11 * self.fRec90[1] - (self.fRec9[1] + self.fRec9[2]));
			self.fRec90[0] = (if (F32::abs(-fTemp207) > 1.1754944e-38) as i32 != 0 {-fTemp207} else {0.0});
			let mut fTemp208: F32 = self.fRec89[0] + self.fSlow12 * self.fRec90[0];
			self.fVec35[0] = fTemp208;
			let mut fTemp209: F32 = self.fSlow7 * (self.fSlow8 * self.fRec88[1] - (fTemp208 + self.fVec35[1]));
			self.fRec88[0] = (if (F32::abs(-fTemp209) > 1.1754944e-38) as i32 != 0 {-fTemp209} else {0.0});
			let mut fTemp210: F32 = self.fSlow7 * (self.fSlow8 * self.fRec91[1] - self.fSlow6 * (fTemp208 - self.fVec35[1]));
			self.fRec91[0] = (if (F32::abs(-fTemp210) > 1.1754944e-38) as i32 != 0 {-fTemp210} else {0.0});
			let mut fTemp211: F32 = self.fSlow46 * (self.fRec88[0] + self.fSlow13 * self.fRec91[0]);
			self.fVec36[(self.IOTA0 & 65535) as usize] = fTemp211;
			let mut iTemp212: i32 = (fTemp200) as i32;
			let mut fTemp213: F32 = 0.16666667 * fTemp204 * fTemp205 * self.fVec36[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp212, 3))) as F32)) as i32)) & 65535) as usize] + fTemp47 + (fTemp199 + (-3.0 - fTemp201)) * (fTemp205 * (0.5 * fTemp202 * self.fVec36[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp212, 1))) as F32)) as i32)) & 65535) as usize] - 0.16666667 * self.fVec36[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp212)) as F32)) as i32)) & 65535) as usize] * fTemp203) - 0.5 * fTemp204 * self.fVec36[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp212, 2))) as F32)) as i32)) & 65535) as usize]) - 0.6 * self.fRec86[1];
			self.fVec37[(self.IOTA0 & 1023) as usize] = fTemp213;
			let mut fTemp214: F32 = self.fVec37[((i32::wrapping_sub(self.IOTA0, 1001)) & 1023) as usize];
			self.fRec86[0] = (if (F32::abs(fTemp214) > 1.1754944e-38) as i32 != 0 {fTemp214} else {0.0});
			let mut fTemp215: F32 = 0.6 * fTemp213;
			let mut fRec87: F32 = (if (F32::abs(fTemp215) > 1.1754944e-38) as i32 != 0 {fTemp215} else {0.0});
			let mut fTemp216: F32 = (if iTemp0 != 0 {0.3125} else {self.fSlow3 + self.fRec94[1]});
			let mut fTemp217: F32 = fTemp216 - F32::floor(fTemp216);
			self.fRec94[0] = (if (F32::abs(fTemp217) > 1.1754944e-38) as i32 != 0 {fTemp217} else {0.0});
			let mut fTemp218: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec94[0]);
			let mut fTemp219: F32 = F32::max(1.0, self.fSlow1 * (0.125 - fTemp218));
			let mut fTemp220: F32 = fTemp219 + -0.999995;
			let mut fTemp221: F32 = F32::floor(fTemp220);
			let mut fTemp222: F32 = fTemp219 - fTemp221;
			let mut fTemp223: F32 = fTemp219 + (-1.0 - fTemp221);
			let mut fTemp224: F32 = fTemp222 * fTemp223;
			let mut fTemp225: F32 = fTemp219 + (-2.0 - fTemp221);
			let mut fTemp226: F32 = self.fSlow10 * (self.fSlow11 * self.fRec96[1] - self.fSlow9 * (self.fRec5[1] - self.fRec5[2]));
			self.fRec96[0] = (if (F32::abs(-fTemp226) > 1.1754944e-38) as i32 != 0 {-fTemp226} else {0.0});
			let mut fTemp227: F32 = self.fSlow10 * (self.fSlow11 * self.fRec97[1] - (self.fRec5[1] + self.fRec5[2]));
			self.fRec97[0] = (if (F32::abs(-fTemp227) > 1.1754944e-38) as i32 != 0 {-fTemp227} else {0.0});
			let mut fTemp228: F32 = self.fRec96[0] + self.fSlow12 * self.fRec97[0];
			self.fVec38[0] = fTemp228;
			let mut fTemp229: F32 = self.fSlow7 * (self.fSlow8 * self.fRec95[1] - (fTemp228 + self.fVec38[1]));
			self.fRec95[0] = (if (F32::abs(-fTemp229) > 1.1754944e-38) as i32 != 0 {-fTemp229} else {0.0});
			let mut fTemp230: F32 = self.fSlow7 * (self.fSlow8 * self.fRec98[1] - self.fSlow6 * (fTemp228 - self.fVec38[1]));
			self.fRec98[0] = (if (F32::abs(-fTemp230) > 1.1754944e-38) as i32 != 0 {-fTemp230} else {0.0});
			let mut fTemp231: F32 = self.fSlow47 * (self.fRec95[0] + self.fSlow13 * self.fRec98[0]);
			self.fVec39[(self.IOTA0 & 131071) as usize] = fTemp231;
			let mut iTemp232: i32 = (fTemp220) as i32;
			let mut fTemp233: F32 = 0.16666667 * fTemp224 * fTemp225 * self.fVec39[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp232, 3))) as F32)) as i32)) & 131071) as usize] + fTemp47 + (fTemp219 + (-3.0 - fTemp221)) * (fTemp225 * (0.5 * fTemp222 * self.fVec39[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp232, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec39[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp232)) as F32)) as i32)) & 131071) as usize] * fTemp223) - 0.5 * fTemp224 * self.fVec39[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp232, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec92[1];
			self.fVec40[(self.IOTA0 & 1023) as usize] = fTemp233;
			let mut fTemp234: F32 = self.fVec40[((i32::wrapping_sub(self.IOTA0, 806)) & 1023) as usize];
			self.fRec92[0] = (if (F32::abs(fTemp234) > 1.1754944e-38) as i32 != 0 {fTemp234} else {0.0});
			let mut fTemp235: F32 = 0.6 * fTemp233;
			let mut fRec93: F32 = (if (F32::abs(fTemp235) > 1.1754944e-38) as i32 != 0 {fTemp235} else {0.0});
			let mut fTemp236: F32 = F32::max(1.0, self.fSlow1 * (fTemp218 + 0.21039456));
			let mut fTemp237: F32 = fTemp236 + -0.999995;
			let mut fTemp238: F32 = F32::floor(fTemp237);
			let mut fTemp239: F32 = fTemp236 - fTemp238;
			let mut fTemp240: F32 = fTemp236 + (-1.0 - fTemp238);
			let mut fTemp241: F32 = fTemp239 * fTemp240;
			let mut fTemp242: F32 = fTemp236 + (-2.0 - fTemp238);
			let mut fTemp243: F32 = self.fSlow10 * (self.fSlow11 * self.fRec102[1] - self.fSlow9 * (self.fRec1[1] - self.fRec1[2]));
			self.fRec102[0] = (if (F32::abs(-fTemp243) > 1.1754944e-38) as i32 != 0 {-fTemp243} else {0.0});
			let mut fTemp244: F32 = self.fSlow10 * (self.fSlow11 * self.fRec103[1] - (self.fRec1[1] + self.fRec1[2]));
			self.fRec103[0] = (if (F32::abs(-fTemp244) > 1.1754944e-38) as i32 != 0 {-fTemp244} else {0.0});
			let mut fTemp245: F32 = self.fRec102[0] + self.fSlow12 * self.fRec103[0];
			self.fVec41[0] = fTemp245;
			let mut fTemp246: F32 = self.fSlow7 * (self.fSlow8 * self.fRec101[1] - (fTemp245 + self.fVec41[1]));
			self.fRec101[0] = (if (F32::abs(-fTemp246) > 1.1754944e-38) as i32 != 0 {-fTemp246} else {0.0});
			let mut fTemp247: F32 = self.fSlow7 * (self.fSlow8 * self.fRec104[1] - self.fSlow6 * (fTemp245 - self.fVec41[1]));
			self.fRec104[0] = (if (F32::abs(-fTemp247) > 1.1754944e-38) as i32 != 0 {-fTemp247} else {0.0});
			let mut fTemp248: F32 = self.fSlow48 * (self.fRec101[0] + self.fSlow13 * self.fRec104[0]);
			self.fVec42[(self.IOTA0 & 131071) as usize] = fTemp248;
			let mut iTemp249: i32 = (fTemp237) as i32;
			let mut fTemp250: F32 = 0.16666667 * fTemp241 * fTemp242 * self.fVec42[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp249, 3))) as F32)) as i32)) & 131071) as usize] + (fTemp236 + (-3.0 - fTemp238)) * (fTemp242 * (0.5 * fTemp239 * self.fVec42[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp249, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec42[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp249)) as F32)) as i32)) & 131071) as usize] * fTemp240) - 0.5 * fTemp241 * self.fVec42[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp249, 2))) as F32)) as i32)) & 131071) as usize]) + fTemp47 - 0.6 * self.fRec99[1];
			self.fVec43[(self.IOTA0 & 1023) as usize] = fTemp250;
			let mut fTemp251: F32 = self.fVec43[((i32::wrapping_sub(self.IOTA0, 798)) & 1023) as usize];
			self.fRec99[0] = (if (F32::abs(fTemp251) > 1.1754944e-38) as i32 != 0 {fTemp251} else {0.0});
			let mut fTemp252: F32 = 0.6 * fTemp250;
			let mut fRec100: F32 = (if (F32::abs(fTemp252) > 1.1754944e-38) as i32 != 0 {fTemp252} else {0.0});
			let mut fTemp253: F32 = (if iTemp0 != 0 {0.0} else {self.fSlow3 + self.fRec107[1]});
			let mut fTemp254: F32 = fTemp253 - F32::floor(fTemp253);
			self.fRec107[0] = (if (F32::abs(fTemp254) > 1.1754944e-38) as i32 != 0 {fTemp254} else {0.0});
			let mut fTemp255: F32 = self.fSlow2 * F32::sin(6.2831855 * self.fRec107[0]);
			let mut fTemp256: F32 = F32::max(1.0, self.fSlow1 * (0.10252925 - fTemp255));
			let mut fTemp257: F32 = fTemp256 + -0.999995;
			let mut fTemp258: F32 = F32::floor(fTemp257);
			let mut fTemp259: F32 = fTemp256 - fTemp258;
			let mut fTemp260: F32 = fTemp256 + (-1.0 - fTemp258);
			let mut fTemp261: F32 = fTemp259 * fTemp260;
			let mut fTemp262: F32 = fTemp256 + (-2.0 - fTemp258);
			let mut fTemp263: F32 = self.fSlow10 * (self.fSlow11 * self.fRec109[1] - self.fSlow9 * (self.fRec12[1] - self.fRec12[2]));
			self.fRec109[0] = (if (F32::abs(-fTemp263) > 1.1754944e-38) as i32 != 0 {-fTemp263} else {0.0});
			let mut fTemp264: F32 = self.fSlow10 * (self.fSlow11 * self.fRec110[1] - (self.fRec12[1] + self.fRec12[2]));
			self.fRec110[0] = (if (F32::abs(-fTemp264) > 1.1754944e-38) as i32 != 0 {-fTemp264} else {0.0});
			let mut fTemp265: F32 = self.fRec109[0] + self.fSlow12 * self.fRec110[0];
			self.fVec44[0] = fTemp265;
			let mut fTemp266: F32 = self.fSlow7 * (self.fSlow8 * self.fRec108[1] - (fTemp265 + self.fVec44[1]));
			self.fRec108[0] = (if (F32::abs(-fTemp266) > 1.1754944e-38) as i32 != 0 {-fTemp266} else {0.0});
			let mut fTemp267: F32 = self.fSlow7 * (self.fSlow8 * self.fRec111[1] - self.fSlow6 * (fTemp265 - self.fVec44[1]));
			self.fRec111[0] = (if (F32::abs(-fTemp267) > 1.1754944e-38) as i32 != 0 {-fTemp267} else {0.0});
			let mut fTemp268: F32 = self.fSlow49 * (self.fRec108[0] + self.fSlow13 * self.fRec111[0]);
			self.fVec45[(self.IOTA0 & 65535) as usize] = fTemp268;
			let mut iTemp269: i32 = (fTemp257) as i32;
			let mut fTemp270: F32 = 0.16666667 * fTemp261 * fTemp262 * self.fVec45[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp269, 3))) as F32)) as i32)) & 65535) as usize] + fTemp22 + (fTemp256 + (-3.0 - fTemp258)) * (fTemp262 * (0.5 * fTemp259 * self.fVec45[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp269, 1))) as F32)) as i32)) & 65535) as usize] - 0.16666667 * self.fVec45[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp269)) as F32)) as i32)) & 65535) as usize] * fTemp260) - 0.5 * fTemp261 * self.fVec45[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp269, 2))) as F32)) as i32)) & 65535) as usize]) - 0.6 * self.fRec105[1];
			self.fVec46[(self.IOTA0 & 1023) as usize] = fTemp270;
			let mut fTemp271: F32 = self.fVec46[((i32::wrapping_sub(self.IOTA0, 832)) & 1023) as usize];
			self.fRec105[0] = (if (F32::abs(fTemp271) > 1.1754944e-38) as i32 != 0 {fTemp271} else {0.0});
			let mut fTemp272: F32 = 0.6 * fTemp270;
			let mut fRec106: F32 = (if (F32::abs(fTemp272) > 1.1754944e-38) as i32 != 0 {fTemp272} else {0.0});
			let mut fTemp273: F32 = F32::max(1.0, self.fSlow1 * (fTemp255 + 0.070764855));
			let mut fTemp274: F32 = fTemp273 + -0.999995;
			let mut fTemp275: F32 = F32::floor(fTemp274);
			let mut fTemp276: F32 = fTemp273 - fTemp275;
			let mut fTemp277: F32 = fTemp273 + (-1.0 - fTemp275);
			let mut fTemp278: F32 = fTemp276 * fTemp277;
			let mut fTemp279: F32 = fTemp273 + (-2.0 - fTemp275);
			let mut fTemp280: F32 = self.fSlow10 * (self.fSlow11 * self.fRec115[1] - self.fSlow9 * (self.fRec8[1] - self.fRec8[2]));
			self.fRec115[0] = (if (F32::abs(-fTemp280) > 1.1754944e-38) as i32 != 0 {-fTemp280} else {0.0});
			let mut fTemp281: F32 = self.fSlow10 * (self.fSlow11 * self.fRec116[1] - (self.fRec8[1] + self.fRec8[2]));
			self.fRec116[0] = (if (F32::abs(-fTemp281) > 1.1754944e-38) as i32 != 0 {-fTemp281} else {0.0});
			let mut fTemp282: F32 = self.fRec115[0] + self.fSlow12 * self.fRec116[0];
			self.fVec47[0] = fTemp282;
			let mut fTemp283: F32 = self.fSlow7 * (self.fSlow8 * self.fRec114[1] - (fTemp282 + self.fVec47[1]));
			self.fRec114[0] = (if (F32::abs(-fTemp283) > 1.1754944e-38) as i32 != 0 {-fTemp283} else {0.0});
			let mut fTemp284: F32 = self.fSlow7 * (self.fSlow8 * self.fRec117[1] - self.fSlow6 * (fTemp282 - self.fVec47[1]));
			self.fRec117[0] = (if (F32::abs(-fTemp284) > 1.1754944e-38) as i32 != 0 {-fTemp284} else {0.0});
			let mut fTemp285: F32 = self.fSlow50 * (self.fRec114[0] + self.fSlow13 * self.fRec117[0]);
			self.fVec48[(self.IOTA0 & 65535) as usize] = fTemp285;
			let mut iTemp286: i32 = (fTemp274) as i32;
			let mut fTemp287: F32 = 0.16666667 * fTemp278 * fTemp279 * self.fVec48[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp286, 3))) as F32)) as i32)) & 65535) as usize] + fTemp22 + (fTemp273 + (-3.0 - fTemp275)) * (fTemp279 * (0.5 * fTemp276 * self.fVec48[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp286, 1))) as F32)) as i32)) & 65535) as usize] - 0.16666667 * self.fVec48[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp286)) as F32)) as i32)) & 65535) as usize] * fTemp277) - 0.5 * fTemp278 * self.fVec48[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp286, 2))) as F32)) as i32)) & 65535) as usize]) - 0.6 * self.fRec112[1];
			self.fVec49[(self.IOTA0 & 1023) as usize] = fTemp287;
			let mut fTemp288: F32 = self.fVec49[((i32::wrapping_sub(self.IOTA0, 956)) & 1023) as usize];
			self.fRec112[0] = (if (F32::abs(fTemp288) > 1.1754944e-38) as i32 != 0 {fTemp288} else {0.0});
			let mut fTemp289: F32 = 0.6 * fTemp287;
			let mut fRec113: F32 = (if (F32::abs(fTemp289) > 1.1754944e-38) as i32 != 0 {fTemp289} else {0.0});
			let mut fTemp290: F32 = F32::max(1.0, self.fSlow1 * (0.21998005 - fTemp3));
			let mut fTemp291: F32 = fTemp290 + -0.999995;
			let mut fTemp292: F32 = F32::floor(fTemp291);
			let mut fTemp293: F32 = fTemp290 - fTemp292;
			let mut fTemp294: F32 = fTemp290 + (-1.0 - fTemp292);
			let mut fTemp295: F32 = fTemp293 * fTemp294;
			let mut fTemp296: F32 = fTemp290 + (-2.0 - fTemp292);
			let mut fTemp297: F32 = self.fSlow10 * (self.fSlow11 * self.fRec121[1] - self.fSlow9 * (self.fRec4[1] - self.fRec4[2]));
			self.fRec121[0] = (if (F32::abs(-fTemp297) > 1.1754944e-38) as i32 != 0 {-fTemp297} else {0.0});
			let mut fTemp298: F32 = self.fSlow10 * (self.fSlow11 * self.fRec122[1] - (self.fRec4[1] + self.fRec4[2]));
			self.fRec122[0] = (if (F32::abs(-fTemp298) > 1.1754944e-38) as i32 != 0 {-fTemp298} else {0.0});
			let mut fTemp299: F32 = self.fRec121[0] + self.fSlow12 * self.fRec122[0];
			self.fVec50[0] = fTemp299;
			let mut fTemp300: F32 = self.fSlow7 * (self.fSlow8 * self.fRec120[1] - (fTemp299 + self.fVec50[1]));
			self.fRec120[0] = (if (F32::abs(-fTemp300) > 1.1754944e-38) as i32 != 0 {-fTemp300} else {0.0});
			let mut fTemp301: F32 = self.fSlow7 * (self.fSlow8 * self.fRec123[1] - self.fSlow6 * (fTemp299 - self.fVec50[1]));
			self.fRec123[0] = (if (F32::abs(-fTemp301) > 1.1754944e-38) as i32 != 0 {-fTemp301} else {0.0});
			let mut fTemp302: F32 = self.fSlow51 * (self.fRec120[0] + self.fSlow13 * self.fRec123[0]);
			self.fVec51[(self.IOTA0 & 131071) as usize] = fTemp302;
			let mut iTemp303: i32 = (fTemp291) as i32;
			let mut fTemp304: F32 = 0.16666667 * fTemp295 * fTemp296 * self.fVec51[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp303, 3))) as F32)) as i32)) & 131071) as usize] + fTemp22 + (fTemp290 + (-3.0 - fTemp292)) * (fTemp296 * (0.5 * fTemp293 * self.fVec51[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp303, 1))) as F32)) as i32)) & 131071) as usize] - 0.16666667 * self.fVec51[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, iTemp303)) as F32)) as i32)) & 131071) as usize] * fTemp294) - 0.5 * fTemp295 * self.fVec51[((i32::wrapping_sub(self.IOTA0, (F32::min(self.fConst3, (std::cmp::max(0, i32::wrapping_add(iTemp303, 2))) as F32)) as i32)) & 131071) as usize]) - 0.6 * self.fRec118[1];
			self.fVec52[(self.IOTA0 & 1023) as usize] = fTemp304;
			let mut fTemp305: F32 = self.fVec52[((i32::wrapping_sub(self.IOTA0, 894)) & 1023) as usize];
			self.fRec118[0] = (if (F32::abs(fTemp305) > 1.1754944e-38) as i32 != 0 {fTemp305} else {0.0});
			let mut fTemp306: F32 = 0.6 * fTemp304;
			let mut fRec119: F32 = (if (F32::abs(fTemp306) > 1.1754944e-38) as i32 != 0 {fTemp306} else {0.0});
			let mut fTemp307: F32 = fRec106 + fRec113 + fRec17 + fRec119;
			let mut fTemp308: F32 = 0.25 * (self.fRec25[1] + self.fRec34[1] + self.fRec40[1] + self.fRec47[1] + self.fRec53[1] + self.fRec60[1] + self.fRec66[1] + self.fRec73[1] + self.fRec79[1] + self.fRec86[1] + self.fRec92[1] + self.fRec99[1] + self.fRec105[1] + self.fRec112[1] + self.fRec118[1] + self.fRec16[1] + fRec26 + fRec35 + fRec41 + fRec48 + fRec54 + fRec61 + fRec67 + fRec74 + fRec80 + fRec87 + fRec93 + fRec100 + fTemp307);
			let mut fTemp309: F32 = self.fRec105[1] + self.fRec112[1] + self.fRec118[1] + self.fRec16[1] + fTemp307;
			let mut fTemp310: F32 = self.fRec47[1] + self.fRec73[1] + self.fRec99[1] + self.fRec16[1] + fRec48 + fRec74 + fRec17 + fRec100;
			let mut fTemp311: F32 = fRec17 + self.fRec16[1] + fTemp308 - 0.5 * (fTemp309 + fTemp310);
			self.fRec0[0] = (if (F32::abs(fTemp311) > 1.1754944e-38) as i32 != 0 {fTemp311} else {0.0});
			let mut fTemp312: F32 = self.fRec79[1] + self.fRec86[1] + self.fRec92[1] + self.fRec99[1] + fRec80 + fRec87 + fRec100 + fRec93;
			let mut fTemp313: F32 = fRec100 + self.fRec99[1] + fTemp308 - 0.5 * (fTemp312 + fTemp310);
			self.fRec1[0] = (if (F32::abs(fTemp313) > 1.1754944e-38) as i32 != 0 {fTemp313} else {0.0});
			let mut fTemp314: F32 = self.fRec53[1] + self.fRec60[1] + self.fRec66[1] + self.fRec73[1] + fRec54 + fRec61 + fRec74 + fRec67;
			let mut fTemp315: F32 = fRec74 + self.fRec73[1] + fTemp308 - 0.5 * (fTemp314 + fTemp310);
			self.fRec2[0] = (if (F32::abs(fTemp315) > 1.1754944e-38) as i32 != 0 {fTemp315} else {0.0});
			let mut fTemp316: F32 = self.fRec25[1] + self.fRec34[1] + self.fRec40[1] + self.fRec47[1] + fRec26 + fRec35 + fRec48 + fRec41;
			let mut fTemp317: F32 = fRec48 + self.fRec47[1] + fTemp308 - 0.5 * (fTemp316 + fTemp310);
			self.fRec3[0] = (if (F32::abs(fTemp317) > 1.1754944e-38) as i32 != 0 {fTemp317} else {0.0});
			let mut fTemp318: F32 = self.fRec40[1] + self.fRec66[1] + self.fRec92[1] + self.fRec118[1] + fRec41 + fRec67 + fRec119 + fRec93;
			let mut fTemp319: F32 = fRec119 + self.fRec118[1] + fTemp308 - 0.5 * (fTemp309 + fTemp318);
			self.fRec4[0] = (if (F32::abs(fTemp319) > 1.1754944e-38) as i32 != 0 {fTemp319} else {0.0});
			let mut fTemp320: F32 = fRec93 + self.fRec92[1] + fTemp308 - 0.5 * (fTemp312 + fTemp318);
			self.fRec5[0] = (if (F32::abs(fTemp320) > 1.1754944e-38) as i32 != 0 {fTemp320} else {0.0});
			let mut fTemp321: F32 = fRec67 + self.fRec66[1] + fTemp308 - 0.5 * (fTemp314 + fTemp318);
			self.fRec6[0] = (if (F32::abs(fTemp321) > 1.1754944e-38) as i32 != 0 {fTemp321} else {0.0});
			let mut fTemp322: F32 = fRec41 + self.fRec40[1] + fTemp308 - 0.5 * (fTemp316 + fTemp318);
			self.fRec7[0] = (if (F32::abs(fTemp322) > 1.1754944e-38) as i32 != 0 {fTemp322} else {0.0});
			let mut fTemp323: F32 = self.fRec34[1] + self.fRec60[1] + self.fRec86[1] + self.fRec112[1] + fRec35 + fRec61 + fRec113 + fRec87;
			let mut fTemp324: F32 = fRec113 + self.fRec112[1] + fTemp308 - 0.5 * (fTemp309 + fTemp323);
			self.fRec8[0] = (if (F32::abs(fTemp324) > 1.1754944e-38) as i32 != 0 {fTemp324} else {0.0});
			let mut fTemp325: F32 = fRec87 + self.fRec86[1] + fTemp308 - 0.5 * (fTemp312 + fTemp323);
			self.fRec9[0] = (if (F32::abs(fTemp325) > 1.1754944e-38) as i32 != 0 {fTemp325} else {0.0});
			let mut fTemp326: F32 = fRec61 + self.fRec60[1] + fTemp308 - 0.5 * (fTemp314 + fTemp323);
			self.fRec10[0] = (if (F32::abs(fTemp326) > 1.1754944e-38) as i32 != 0 {fTemp326} else {0.0});
			let mut fTemp327: F32 = fRec35 + self.fRec34[1] + fTemp308 - 0.5 * (fTemp316 + fTemp323);
			self.fRec11[0] = (if (F32::abs(fTemp327) > 1.1754944e-38) as i32 != 0 {fTemp327} else {0.0});
			let mut fTemp328: F32 = self.fRec25[1] + self.fRec53[1] + self.fRec79[1] + self.fRec105[1] + fRec26 + fRec54 + fRec106 + fRec80;
			let mut fTemp329: F32 = fRec106 + self.fRec105[1] + fTemp308 - 0.5 * (fTemp309 + fTemp328);
			self.fRec12[0] = (if (F32::abs(fTemp329) > 1.1754944e-38) as i32 != 0 {fTemp329} else {0.0});
			let mut fTemp330: F32 = fRec80 + self.fRec79[1] + fTemp308 - 0.5 * (fTemp312 + fTemp328);
			self.fRec13[0] = (if (F32::abs(fTemp330) > 1.1754944e-38) as i32 != 0 {fTemp330} else {0.0});
			let mut fTemp331: F32 = fRec54 + self.fRec53[1] + fTemp308 - 0.5 * (fTemp314 + fTemp328);
			self.fRec14[0] = (if (F32::abs(fTemp331) > 1.1754944e-38) as i32 != 0 {fTemp331} else {0.0});
			let mut fTemp332: F32 = fRec26 + self.fRec25[1] + fTemp308 - 0.5 * (fTemp316 + fTemp328);
			self.fRec15[0] = (if (F32::abs(fTemp332) > 1.1754944e-38) as i32 != 0 {fTemp332} else {0.0});
			*output0 = self.fRec1[0] + self.fRec3[0] + self.fRec5[0] + self.fRec7[0] + self.fRec9[0] + self.fRec11[0] + self.fRec13[0] + self.fRec15[0];
			*output1 = self.fRec0[0] + self.fRec2[0] + self.fRec4[0] + self.fRec6[0] + self.fRec8[0] + self.fRec10[0] + self.fRec12[0] + self.fRec14[0];
			self.iVec0[1] = self.iVec0[0];
			self.fRec18[1] = self.fRec18[0];
			self.fRec20[1] = self.fRec20[0];
			self.fRec21[1] = self.fRec21[0];
			self.fVec1[1] = self.fVec1[0];
			self.fRec19[1] = self.fRec19[0];
			self.fRec22[1] = self.fRec22[0];
			self.IOTA0 = i32::wrapping_add(self.IOTA0, 1);
			self.fVec4[1] = self.fVec4[0];
			self.fRec24[1] = self.fRec24[0];
			self.fRec23[1] = self.fRec23[0];
			self.fRec16[1] = self.fRec16[0];
			self.fRec27[1] = self.fRec27[0];
			self.fRec29[1] = self.fRec29[0];
			self.fRec30[1] = self.fRec30[0];
			self.fVec6[1] = self.fVec6[0];
			self.fRec28[1] = self.fRec28[0];
			self.fRec31[1] = self.fRec31[0];
			self.fVec9[1] = self.fVec9[0];
			self.fRec33[1] = self.fRec33[0];
			self.fRec32[1] = self.fRec32[0];
			self.fRec25[1] = self.fRec25[0];
			self.fRec37[1] = self.fRec37[0];
			self.fRec38[1] = self.fRec38[0];
			self.fVec11[1] = self.fVec11[0];
			self.fRec36[1] = self.fRec36[0];
			self.fRec39[1] = self.fRec39[0];
			self.fRec34[1] = self.fRec34[0];
			self.fRec42[1] = self.fRec42[0];
			self.fRec44[1] = self.fRec44[0];
			self.fRec45[1] = self.fRec45[0];
			self.fVec14[1] = self.fVec14[0];
			self.fRec43[1] = self.fRec43[0];
			self.fRec46[1] = self.fRec46[0];
			self.fRec40[1] = self.fRec40[0];
			self.fRec50[1] = self.fRec50[0];
			self.fRec51[1] = self.fRec51[0];
			self.fVec17[1] = self.fVec17[0];
			self.fRec49[1] = self.fRec49[0];
			self.fRec52[1] = self.fRec52[0];
			self.fRec47[1] = self.fRec47[0];
			self.fRec55[1] = self.fRec55[0];
			self.fRec57[1] = self.fRec57[0];
			self.fRec58[1] = self.fRec58[0];
			self.fVec20[1] = self.fVec20[0];
			self.fRec56[1] = self.fRec56[0];
			self.fRec59[1] = self.fRec59[0];
			self.fRec53[1] = self.fRec53[0];
			self.fRec63[1] = self.fRec63[0];
			self.fRec64[1] = self.fRec64[0];
			self.fVec23[1] = self.fVec23[0];
			self.fRec62[1] = self.fRec62[0];
			self.fRec65[1] = self.fRec65[0];
			self.fRec60[1] = self.fRec60[0];
			self.fRec68[1] = self.fRec68[0];
			self.fRec70[1] = self.fRec70[0];
			self.fRec71[1] = self.fRec71[0];
			self.fVec26[1] = self.fVec26[0];
			self.fRec69[1] = self.fRec69[0];
			self.fRec72[1] = self.fRec72[0];
			self.fRec66[1] = self.fRec66[0];
			self.fRec76[1] = self.fRec76[0];
			self.fRec77[1] = self.fRec77[0];
			self.fVec29[1] = self.fVec29[0];
			self.fRec75[1] = self.fRec75[0];
			self.fRec78[1] = self.fRec78[0];
			self.fRec73[1] = self.fRec73[0];
			self.fRec81[1] = self.fRec81[0];
			self.fRec83[1] = self.fRec83[0];
			self.fRec84[1] = self.fRec84[0];
			self.fVec32[1] = self.fVec32[0];
			self.fRec82[1] = self.fRec82[0];
			self.fRec85[1] = self.fRec85[0];
			self.fRec79[1] = self.fRec79[0];
			self.fRec89[1] = self.fRec89[0];
			self.fRec90[1] = self.fRec90[0];
			self.fVec35[1] = self.fVec35[0];
			self.fRec88[1] = self.fRec88[0];
			self.fRec91[1] = self.fRec91[0];
			self.fRec86[1] = self.fRec86[0];
			self.fRec94[1] = self.fRec94[0];
			self.fRec96[1] = self.fRec96[0];
			self.fRec97[1] = self.fRec97[0];
			self.fVec38[1] = self.fVec38[0];
			self.fRec95[1] = self.fRec95[0];
			self.fRec98[1] = self.fRec98[0];
			self.fRec92[1] = self.fRec92[0];
			self.fRec102[1] = self.fRec102[0];
			self.fRec103[1] = self.fRec103[0];
			self.fVec41[1] = self.fVec41[0];
			self.fRec101[1] = self.fRec101[0];
			self.fRec104[1] = self.fRec104[0];
			self.fRec99[1] = self.fRec99[0];
			self.fRec107[1] = self.fRec107[0];
			self.fRec109[1] = self.fRec109[0];
			self.fRec110[1] = self.fRec110[0];
			self.fVec44[1] = self.fVec44[0];
			self.fRec108[1] = self.fRec108[0];
			self.fRec111[1] = self.fRec111[0];
			self.fRec105[1] = self.fRec105[0];
			self.fRec115[1] = self.fRec115[0];
			self.fRec116[1] = self.fRec116[0];
			self.fVec47[1] = self.fVec47[0];
			self.fRec114[1] = self.fRec114[0];
			self.fRec117[1] = self.fRec117[0];
			self.fRec112[1] = self.fRec112[0];
			self.fRec121[1] = self.fRec121[0];
			self.fRec122[1] = self.fRec122[0];
			self.fVec50[1] = self.fVec50[0];
			self.fRec120[1] = self.fRec120[0];
			self.fRec123[1] = self.fRec123[0];
			self.fRec118[1] = self.fRec118[0];
			self.fRec0[2] = self.fRec0[1];
			self.fRec0[1] = self.fRec0[0];
			self.fRec1[2] = self.fRec1[1];
			self.fRec1[1] = self.fRec1[0];
			self.fRec2[2] = self.fRec2[1];
			self.fRec2[1] = self.fRec2[0];
			self.fRec3[2] = self.fRec3[1];
			self.fRec3[1] = self.fRec3[0];
			self.fRec4[2] = self.fRec4[1];
			self.fRec4[1] = self.fRec4[0];
			self.fRec5[2] = self.fRec5[1];
			self.fRec5[1] = self.fRec5[0];
			self.fRec6[2] = self.fRec6[1];
			self.fRec6[1] = self.fRec6[0];
			self.fRec7[2] = self.fRec7[1];
			self.fRec7[1] = self.fRec7[0];
			self.fRec8[2] = self.fRec8[1];
			self.fRec8[1] = self.fRec8[0];
			self.fRec9[2] = self.fRec9[1];
			self.fRec9[1] = self.fRec9[0];
			self.fRec10[2] = self.fRec10[1];
			self.fRec10[1] = self.fRec10[0];
			self.fRec11[2] = self.fRec11[1];
			self.fRec11[1] = self.fRec11[0];
			self.fRec12[2] = self.fRec12[1];
			self.fRec12[1] = self.fRec12[0];
			self.fRec13[2] = self.fRec13[1];
			self.fRec13[1] = self.fRec13[0];
			self.fRec14[2] = self.fRec14[1];
			self.fRec14[1] = self.fRec14[0];
			self.fRec15[2] = self.fRec15[1];
			self.fRec15[1] = self.fRec15[0];
		}
		
	}

}

impl FaustDsp for VitalRevDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
