// @generated by dsp/regen.sh from dsp/wah.dsp — DO NOT EDIT (faust 2.81.2)
/* ------------------------------------------------------------
name: "wah"
Code generated with Faust 2.81.2 (https://faust.grame.fr)
Compilation options: -lang rust -ec -ct 1 -cn WahDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */
#[repr(C)]
pub struct WahDsp {
	fHslider0: F32,
	fSlow0: F32,
	fSlow1: F32,
	fSampleRate: i32,
	fConst0: F32,
	fConst1: F32,
	fConst2: F32,
	fHslider1: F32,
	fSlow2: F32,
	fHslider2: F32,
	fSlow3: F32,
	fConst3: F32,
	fConst4: F32,
	fRec3: [F32;2],
	fHslider3: F32,
	fSlow4: F32,
	fRec0: [F32;2],
	fRec1: [F32;2],
}

pub type FaustFloat = F32;
fn remainder_f32(from: f32, to: f32) -> f32 {
	from - to * (from / to).round_ties_even()
}
fn rint_f32(val: f32) -> f32 {
	val.round_ties_even()
}

pub const FAUST_INPUTS: usize = 1;
pub const FAUST_OUTPUTS: usize = 1;
pub const FAUST_ACTIVES: usize = 4;
pub const FAUST_PASSIVES: usize = 0;


impl WahDsp {
		
	pub fn new() -> WahDsp { 
		WahDsp {
			fHslider0: 0.0,
			fSlow0: 0.0,
			fSlow1: 0.0,
			fSampleRate: 0,
			fConst0: 0.0,
			fConst1: 0.0,
			fConst2: 0.0,
			fHslider1: 0.0,
			fSlow2: 0.0,
			fHslider2: 0.0,
			fSlow3: 0.0,
			fConst3: 0.0,
			fConst4: 0.0,
			fRec3: [0.0;2],
			fHslider3: 0.0,
			fSlow4: 0.0,
			fRec0: [0.0;2],
			fRec1: [0.0;2],
		}
	}
	pub fn metadata(&self, m: &mut dyn Meta) { 
		m.declare("analyzers.lib/name", r"Faust Analyzer Library");
		m.declare("analyzers.lib/version", r"1.2.0");
		m.declare("basics.lib/name", r"Faust Basic Element Library");
		m.declare("basics.lib/version", r"1.21.0");
		m.declare("compile_options", r"-lang rust -ec -ct 1 -cn WahDsp -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0");
		m.declare("filename", r"wah.dsp");
		m.declare("filters.lib/lowpass0_highpass1", r"Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m.declare("filters.lib/name", r"Faust Filters Library");
		m.declare("filters.lib/svf:author", r"Oleg Nesterov");
		m.declare("filters.lib/svf:copyright", r"Copyright (C) 2020 Oleg Nesterov <oleg@redhat.com>");
		m.declare("filters.lib/svf:license", r"MIT-style STK-4.3 license");
		m.declare("filters.lib/version", r"1.7.1");
		m.declare("maths.lib/author", r"GRAME");
		m.declare("maths.lib/copyright", r"GRAME");
		m.declare("maths.lib/license", r"LGPL with exception");
		m.declare("maths.lib/name", r"Faust Math Library");
		m.declare("maths.lib/version", r"2.8.1");
		m.declare("name", r"wah");
		m.declare("platform.lib/name", r"Generic Platform Library");
		m.declare("platform.lib/version", r"1.3.0");
		m.declare("routes.lib/name", r"Faust Signal Routing Library");
		m.declare("routes.lib/version", r"1.2.0");
		m.declare("signals.lib/name", r"Faust Signal Routing Library");
		m.declare("signals.lib/version", r"1.6.0");
	}

	pub fn get_sample_rate(&self) -> i32 { self.fSampleRate as i32}
	
	pub fn class_init(sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
	}
	pub fn instance_reset_params(&mut self) {
		self.fHslider0 = 0.0;
		self.fHslider1 = 4e+02;
		self.fHslider2 = 0.5;
		self.fHslider3 = 0.5;
	}
	pub fn instance_clear(&mut self) {
		for l0 in 0..2 {
			self.fRec3[l0 as usize] = 0.0;
		}
		for l1 in 0..2 {
			self.fRec0[l1 as usize] = 0.0;
		}
		for l2 in 0..2 {
			self.fRec1[l2 as usize] = 0.0;
		}
	}
	pub fn instance_constants(&mut self, sample_rate: i32) {
		// Obtaining locks on 0 static var(s)
		self.fSampleRate = sample_rate;
		self.fConst0 = F32::min(1.92e+05, F32::max(1.0, (self.fSampleRate) as F32));
		self.fConst1 = 3.1415927 / self.fConst0;
		self.fConst2 = 0.45 * self.fConst0;
		self.fConst3 = F32::exp(-(1e+02 / self.fConst0));
		self.fConst4 = 1.0 - self.fConst3;
	}
	pub fn instance_init(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate);
		self.instance_reset_params();
		self.instance_clear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		WahDsp::class_init(sample_rate);
		self.instance_init(sample_rate);
	}
	
	pub fn build_user_interface(&self, ui_interface: &mut dyn UI<FaustFloat>) {
		Self::build_user_interface_static(ui_interface);
	}
	
	pub fn build_user_interface_static(ui_interface: &mut dyn UI<FaustFloat>) {
		ui_interface.open_vertical_box("wah");
		ui_interface.add_horizontal_slider("a_wah", ParamIndex(0), 0.0, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("b_peak", ParamIndex(1), 0.5, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("c_sens", ParamIndex(2), 0.5, 0.0, 1.0, 0.001);
		ui_interface.add_horizontal_slider("d_manual", ParamIndex(3), 4e+02, 1e+02, 4e+03, 0.1);
		ui_interface.close_box();
	}
	
	pub fn get_param(&self, param: ParamIndex) -> Option<FaustFloat> {
		match param.0 {
			0 => Some(self.fHslider0),
			3 => Some(self.fHslider1),
			2 => Some(self.fHslider2),
			1 => Some(self.fHslider3),
			_ => None,
		}
	}
	
	pub fn set_param(&mut self, param: ParamIndex, value: FaustFloat) {
		match param.0 {
			0 => { self.fHslider0 = value }
			3 => { self.fHslider1 = value }
			2 => { self.fHslider2 = value }
			1 => { self.fHslider3 = value }
			_ => {}
		}
	}
	
	pub fn control(&mut self) {
		// Obtaining locks on 0 static var(s)
	self.fSlow0 = self.fHslider0;
		self.fSlow1 = 1.0 - self.fSlow0;
		self.fSlow2 = self.fHslider1;
		self.fSlow3 = 4e+03 * self.fHslider2;
		self.fSlow4 = 1.0 / (18.0 * F32::max(0.0, F32::min(1.0, self.fHslider3)) + 2.0);
	}
	
	pub fn compute(
		&mut self,
		count: usize,
		inputs: &[impl AsRef<[FaustFloat]>],
		outputs: &mut[impl AsMut<[FaustFloat]>],
	) {
		
		// Obtaining locks on 0 static var(s)
		let [inputs0, .. ] = inputs.as_ref() else { panic!("wrong number of input buffers"); };
		let inputs0 = inputs0.as_ref()[..count].iter();
		let [outputs0, .. ] = outputs.as_mut() else { panic!("wrong number of output buffers"); };
		let outputs0 = outputs0.as_mut()[..count].iter_mut();
		let zipped_iterators = inputs0.zip(outputs0);
		for (input0, output0) in zipped_iterators {
			let mut fTemp0: F32 = *input0;
			let mut fTemp1: F32 = F32::abs(fTemp0);
			self.fRec3[0] = F32::max(fTemp1, self.fConst3 * self.fRec3[1] + self.fConst4 * fTemp1);
			let mut fTemp2: F32 = F32::tan(self.fConst1 * F32::max(2e+01, F32::min(self.fConst2, self.fSlow2 + self.fSlow3 * self.fRec3[0])));
			let mut fTemp3: F32 = self.fRec0[1] + fTemp2 * (fTemp0 - self.fRec1[1]);
			let mut fTemp4: F32 = fTemp2 * (self.fSlow4 + fTemp2) + 1.0;
			let mut fTemp5: F32 = fTemp3 / fTemp4;
			self.fRec0[0] = 2.0 * fTemp5 - self.fRec0[1];
			let mut fTemp6: F32 = self.fRec1[1] + fTemp2 * fTemp3 / fTemp4;
			self.fRec1[0] = 2.0 * fTemp6 - self.fRec1[1];
			let mut fRec2: F32 = fTemp5;
			*output0 = self.fSlow1 * fTemp0 + self.fSlow0 * fRec2;
			self.fRec3[1] = self.fRec3[0];
			self.fRec0[1] = self.fRec0[0];
			self.fRec1[1] = self.fRec1[0];
		}
		
	}

}

impl FaustDsp for WahDsp {
	type T = FaustFloat;
	fn new() -> Self where Self: Sized {
		Self::new()
	}
	fn metadata(&self, m: &mut dyn Meta) {
		self.metadata(m)
	}
	fn get_sample_rate(&self) -> i32 {
		self.get_sample_rate()
	}
	fn get_num_inputs(&self) -> i32 {
		FAUST_INPUTS as i32
	}
	fn get_num_outputs(&self) -> i32 {
		FAUST_OUTPUTS as i32
	}
	fn class_init(sample_rate: i32) where Self: Sized {
		Self::class_init(sample_rate);
	}
	fn instance_reset_params(&mut self) {
		self.instance_reset_params()
	}
	fn instance_clear(&mut self) {
		self.instance_clear()
	}
	fn instance_constants(&mut self, sample_rate: i32) {
		self.instance_constants(sample_rate)
	}
	fn instance_init(&mut self, sample_rate: i32) {
		self.instance_init(sample_rate)
	}
	fn init(&mut self, sample_rate: i32) {
		self.init(sample_rate)
	}
	fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>) {
		self.build_user_interface(ui_interface)
	}
	fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>) where Self: Sized {
		Self::build_user_interface_static(ui_interface);
	}
	fn get_param(&self, param: ParamIndex) -> Option<Self::T> {
		self.get_param(param)
	}
	fn set_param(&mut self, param: ParamIndex, value: Self::T) {
		self.set_param(param, value)
	}
	fn compute(&mut self, count: i32, inputs: &[&[Self::T]], outputs: &mut [&mut [Self::T]]) {
		self.compute(count as usize, inputs, outputs)
	}
}
