use crate::types::{ModuleGroup, ModuleInfo, ParamInfo, ReverbType};

#[derive(Clone, Copy)]
pub struct ReverbParams {
    pub verb_type: ReverbType,
    pub decay: f32,
    pub damp: f32,
    pub predelay: f32,
    pub diff: f32,
    pub size: f32,
    pub prelow: f32,
    pub prehigh: f32,
    pub lowcut: f32,
    pub highcut: f32,
    pub lowgain: f32,
    pub highgain: f32,
    pub chorus: f32,
    pub chorus_freq: f32,
}

impl Default for ReverbParams {
    fn default() -> Self {
        Self {
            verb_type: ReverbType::Space,
            decay: 0.55,
            damp: 0.7,
            predelay: 0.0,
            diff: 0.6,
            size: 0.75,
            prelow: 0.2,
            prehigh: 0.9,
            lowcut: 0.5,
            highcut: 0.7,
            lowgain: 0.1,
            highgain: 0.5,
            chorus: 0.3,
            chorus_freq: 0.65,
        }
    }
}

pub const INFO: ModuleInfo = ModuleInfo {
    name: "reverb",
    description: "Reverb (plate / space algorithms)",
    group: ModuleGroup::Effect,
    params: &[
        ParamInfo {
            name: "verb",
            aliases: &["reverb"],
            description: "send level",
            default: "0.0",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbtype",
            aliases: &["vtype"],
            description: "algorithm (cloud, space)",
            default: "1.0",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbdecay",
            aliases: &[],
            description: "decay time",
            default: "0.55",
            min: 0.0,
            max: 0.99,
        },
        ParamInfo {
            name: "verbdamp",
            aliases: &[],
            description: "damping",
            default: "0.7",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbpredelay",
            aliases: &[],
            description: "pre-delay (0-1, space only)",
            default: "0.0",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbsize",
            aliases: &["vsize"],
            description: "room size",
            default: "0.75",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbdiff",
            aliases: &[],
            description: "diffusion amount",
            default: "0.6",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbprelow",
            aliases: &[],
            description: "pre-filter low cutoff (space only)",
            default: "0.2",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbprehigh",
            aliases: &[],
            description: "pre-filter high cutoff (space only)",
            default: "0.9",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verblowcut",
            aliases: &[],
            description: "low/mid crossover",
            default: "0.5",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbhighcut",
            aliases: &[],
            description: "mid/high crossover",
            default: "0.7",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verblowgain",
            aliases: &[],
            description: "low-band gain",
            default: "0.4",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbhighgain",
            aliases: &[],
            description: "high-band gain",
            default: "0.5",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbchorus",
            aliases: &["vchorus"],
            description: "modulation/chorus amount",
            default: "0.3",
            min: 0.0,
            max: 1.0,
        },
        ParamInfo {
            name: "verbchorusfreq",
            aliases: &["vchorusfreq"],
            description: "modulation/chorus frequency",
            default: "0.65",
            min: 0.0,
            max: 1.0,
        },
    ],
};
